apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
        - name: "database-migrate-ARG_TIMESTAMP"
          image: "ARG_IMAGE:ARG_TAG"
          args: ["ARG_ACTION"]
          volumeMounts:
            - name: migration-secret-files
              mountPath: /etc/cexiolabs/migration/secrets
              readOnly: true
          env:
            - name: LOG_LEVEL
              value: trace
          envFrom:
            - configMapRef:
                name: migration-envvars
      volumes:
        - name: migration-secret-files
          secret:
            secretName: migration
      restartPolicy: Never
  backoffLimit: 5
  # The activeDeadlineSeconds applies to the duration of the job, no matter how many Pods are created.
  # Once a Job reaches activeDeadlineSeconds, all of its running Pods are terminated and
  #   the Job status will become type: Failed with reason: DeadlineExceeded.
  activeDeadlineSeconds: 600
