# kubectl --namespace cexiopay-evolution get --output=yaml ConfigMap/messengerbridge-files
# kubectl --namespace cexiopay-evolution apply --filename=runtime.configmaps/evolution/messengerbridge-files.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cexiopay-evolution
  name: messengerbridge-files
data:
  messenger-bridge.toml: |-
    # File format: https://github.com/toml-lang/toml


    # Select Web servers to be used (splitted by space)
    server_indexer = "apiSrv"

    # Select endpoints to be used (splitted by space)
    endpoint_indexer = "rest welcome"

    # Select messengers to be used
    messenger_indexer = "cryptopay_devel_bot"

    [[server]]
      # Declare an API HTTP server
      index = "apiSrv"
      type = "https"
      listenHost = "0.0.0.0"
      listenPort = 8443
      trustProxy = true
      clientCertificateMode = "none"
      serverCertificate = "/etc/cexiolabs/cexiopay/ssl/tls.crt"
      serverKey = "/etc/cexiolabs/cexiopay/ssl/tls.key"

    [[endpoint]]
      # Declare REST endpoint and bound to the API HTTP server on path /v1
      index = "rest"
      type = "rest"
      servers = "apiSrv"
      bindPath = "/v1"

    [[endpoint]]
      # Declare Welcome Page endpoint and bound to the API HTTP server on path /
      index = "welcome"
      type = "welcome-page"
      servers = "apiSrv"
      bindPath = "/" 


    [approvement]
      # Select topics to be enabled
      topic_indexer = "AcceptDepositApprove ZeroConfirmationApprove"

      [[approvement.topic]]
        index = "ZeroConfirmationApprove"
        description = "Manual approve of zero confirmation."
        requireVotes = 2
        expireTimeout = 600

      [[approvement.topic]]
        index = "AcceptDepositApprove"
        description = "Manual approve of number of confirmations (blockchain specific)."
        requireVotes = 2
        expireTimeout = 300

    [[messenger]]
      index = "cryptopay_devel_bot"
      type = "telegram"
      #apiToken = <bot API token>
      approvementTopicBinding_indexer = "AcceptDepositApproveBinding ZeroConfirmationApproveBinding"

      [[messenger.approvementTopicBinding]]
        index = "ZeroConfirmationApproveBinding"
        bindTopic = "ZeroConfirmationApprove"
        #chatId = <Telegram's Unique identifier for the target chat or username of the target channel (in the format @channelusername)>
        renderTemplate = """
    <b>!TESTNET! Запрос на ручное подтверждение 0-confirmation (нет колбека от pss-provider-wtf2)</b>
    <i>Order: </i><a href="https://board-evolution-cexiopay.dev.kube/order/{{cpoOrderId}}">{{cpoOrderId}}</a>
    <i>Amount: </i><b>{{amount}} {{currency}}</b>
    <i>Deposit address: </i><a href="https://blockstream.info/testnet/address/{{depositAddress}}/">{{depositAddress}}</a>. See also <a href="https://live.blockcypher.com/btc-testnet/address/{{depositAddress}}/">BlockCypher</a>, <a href="https://www.blockchain.com/btc-testnet/address/{{depositAddress}}">BlockchainInfo</a>.
    <i>Input TX hash: </i><a href="https://live.blockcypher.com/btc-testnet/tx/{{txHash}}/">{{txHash}}</a>. See also <a href="https://blockstream.info/testnet/tx/{{txHash}}">BlockCypher</a>, <a href="https://www.blockchain.com/btc-testnet/tx/{{txHash}}">BlockchainInfo</a>.
    """

      [[messenger.approvementTopicBinding]]
        index = "AcceptDepositApproveBinding"
        bindTopic = "AcceptDepositApprove"
        #chatId = <Telegram's Unique identifier for the target chat or username of the target channel (in the format @channelusername)>
        renderTemplate = """
    <b>!TESTNET! Запрос на ручное подтверждение депозита по достижению {{confirmations}}-confirmations (нет колбеков от pss-provider-wtf2)</b>
    <i>Order: </i><a href="https://board-evolution-cexiopay.dev.kube/order/{{cpoOrderId}}">{{cpoOrderId}}</a>
    <i>Amount: </i><b>{{amount}} {{currency}}</b>
    <i>Public confirmations: </i><a href="https://live.blockcypher.com/btc-testnet/tx/{{txHash}}/">{{confirmations}}</a>
    <i>Deposit address: </i><a href="https://blockstream.info/testnet/address/{{depositAddress}}/">{{depositAddress}}</a>. See also <a href="https://live.blockcypher.com/btc-testnet/address/{{depositAddress}}/">BlockCypher</a>, <a href="https://www.blockchain.com/btc-testnet/address/{{depositAddress}}">BlockchainInfo</a>.
    <i>Input TX hash: </i><a href="https://live.blockcypher.com/btc-testnet/tx/{{txHash}}/">{{txHash}}</a>. See also <a href="https://blockstream.info/testnet/tx/{{txHash}}">BlockCypher</a>, <a href="https://www.blockchain.com/btc-testnet/tx/{{txHash}}">BlockchainInfo</a>.
    """
