# kubectl --namespace cexpay-evolution-admin get --output=yaml ConfigMap/ptinvoice-envvars -o yaml
# kubectl --namespace cexpay-evolution-admin get --output=json ConfigMap/ptinvoice-envvars | jq -r ".data" | yq eval -P | sed 's/^/  /'
# kubectl --namespace cexpay-evolution-admin apply --filename=runtime.configmaps/evolution/ptinvoice-envvars.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ptinvoice-envvars
  namespace: cexpay-evolution-admin
