.functions: &functions |
  function verify_runtime_version() {
    if [ -z "${CI_COMMIT_TAG}" ]; then
      echo "The function verify_runtime_version() is able to use for tags only. Variable CI_COMMIT_TAG is not set." >&2
      exit 127
    fi
    local EXPECTED_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/^runtime-//g')
    local HELM_CHART_APP_VERSION=$(grep -e '^appVersion:' Chart.yaml | cut -d ':' -f 2)
    if [ "runtime-$HELM_CHART_APP_VERSION" != "$CI_COMMIT_TAG" ]; then
      echo "Helm Chart appVersion '${HELM_CHART_APP_VERSION}' is not same as tag version '${EXPECTED_VERSION}'. Your tag should named as 'runtime-$HELM_CHART_APP_VERSION' for the case." >&2
      exit 255
    fi
  }
  function verify_imagetag_var() {
    if [ -z "${IMAGE_TAG}" ]; then
      echo "Variable IMAGE_TAG is not set." >&2
      echo "Expected IMAGE_TAG: '<branch>.<commit_sha_head>'' or tag name (like 2.x.x)"
      exit 127
    fi
  }
  function verify_target_var() {
    if [ -z "${TARGET}" ]; then
      echo "Variable TARGET is not set." >&2
      echo "Expected TARGET: "tag" or branch name" >&2
      exit 127
    fi
  }
  function kube_config_setup() {
    if [ -z "${KUBECONF_BASE64}" ]; then
      echo "kube_deploy_dev_image() wrong arguments. Expected environment variable KUBECONF_BASE64" >&2
      exit 1
    fi
    mkdir -p ~/.kube
    echo "$KUBECONF_BASE64" | base64 -d > ~/.kube/config
  }

image:
  name: alpine/helm:2.14.0
  entrypoint: [""]

before_script:
  - *functions

stages:
  - deploy
  - rollback

# Runtime deployment master/dev
devel-1EVO:install:runtime:
  stage: deploy
  script:
    - kube_config_setup
    - cd runtime
    - helm --tiller-namespace "cryptopay-evolution" upgrade --install --namespace "cryptopay-evolution" --values "values.evolution.yaml" --set "docker.processing.tag=$DEVEL_RUNTIME" --set "docker.dashboardserve.tag=$DEVEL_RUNTIME" --set "docker.gatewayserve.tag=$DEVEL_RUNTIME" "$DEVEL_RUNTIME" .
  when: manual
  environment:
    name: evolution
    url: https://$DEVEL_RUNTIME-evolution-cryptopay.dev.kube
  only:
    variables:
      - $DEVEL_RUNTIME =~ /^master|dev|latest$/

devel-2PRSN:install:runtime:
  stage: deploy
  script:
    - kube_config_setup
    - cd runtime
    - helm --tiller-namespace "cryptopay-presentation" upgrade --install --namespace "cryptopay-presentation" --values "values.presentation.yaml" --set "docker.processing.tag=$DEVEL_RUNTIME" --set "docker.dashboardserve.tag=$DEVEL_RUNTIME" --set "docker.gatewayserve.tag=$DEVEL_RUNTIME" "$DEVEL_RUNTIME" .
  when: manual
  environment:
    name: presentation
    url: https://$DEVEL_RUNTIME-presentation-cryptopay.dev.kube
  only:
    variables:
      - $DEVEL_RUNTIME =~ /^master|dev|latest$/


# Runtime deployment TAGs
1EVO:install:runtime:
  stage: deploy
  script:
    - verify_runtime_version
    - kube_config_setup
    - cd runtime
    - helm --tiller-namespace "cryptopay-evolution" upgrade --install --namespace "cryptopay-evolution" --values "values.evolution.yaml" tag .
  when: manual
  environment:
    name: evolution
    url: https://evolution-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^runtime-.*/

2PRSN:install:runtime:
  stage: deploy
  script:
    - verify_runtime_version
    - kube_config_setup
    - cd runtime
    - helm --tiller-namespace "cryptopay-presentation" upgrade --install --namespace "cryptopay-presentation" --values "values.presentation.yaml" tag .
  when: manual
  environment:
    name: presentation
    url: https://presentation-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^runtime-.*/

4PROD:install:runtime:
  stage: deploy
  script:
    - verify_runtime_version
    - kube_config_setup
    - cd runtime
    - helm --tiller-namespace "cryptopay-production" upgrade --install --namespace "cryptopay-production" --values "values.production.yaml" tag .
  when: manual
  environment:
    name: production
    url: https://cryptopay.band/
  only:
    variables:
      - $TARGET == "processing"
      - $ENVIRONMENT == "production"
    refs:
      - tags
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^runtime-.*/


#
#
# Database migration master/dev
#
#
devel-1EVO:install:db:
  image:
    name: harbor.infra.kube/infra/helm
    entrypoint: [""]
  stage: deploy
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=evolution --image=devdocker.infra.kube/cryptopay/database-evolution --tag="$DEVEL_DB_IMAGE_TAG" --install
  when: manual
  environment:
    name: evolution
    url: https://evolution-cryptopay.dev.kube
  only:
    variables:
      - $DEVEL_DB_IMAGE_TAG

devel-1EVO:rollback:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: rollback
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=evolution --image=devdocker.infra.kube/cryptopay/database-evolution --tag="$DEVEL_DB_IMAGE_TAG" --rollback
  when: manual
  environment:
    name: evolution
    url: https://evolution-cryptopay.dev.kube
  only:
    variables:
      - $DEVEL_DB_IMAGE_TAG

devel-2PRSN:install:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=presentation --image=devdocker.infra.kube/cryptopay/database-presentation --tag="$DEVEL_DB_IMAGE_TAG" --install
  when: manual
  environment:
    name: presentation
    url: https://presentation-cryptopay.dev.kube
  only:
    variables:
      - $DEVEL_DB_IMAGE_TAG

devel-2PRSN:rollback:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: rollback
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=presentation --image=devdocker.infra.kube/cryptopay/database-presentation --tag="$DEVEL_DB_IMAGE_TAG" --rollback
  when: manual
  environment:
    name: presentation
    url: https://presentation-cryptopay.dev.kube
  only:
    variables:
      - $DEVEL_DB_IMAGE_TAG

#
#
# Database migration TAGs
#
#
1EVO:install:db:
  image:
    name: harbor.infra.kube/infra/helm
    entrypoint: [""]
  stage: deploy
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=evolution --image=devdocker.infra.kube/cryptopay/database-evolution --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --install
  when: manual
  environment:
    name: evolution
    url: https://evolution-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

1EVO:rollback:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: rollback
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=evolution --image=devdocker.infra.kube/cryptopay/database-evolution --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --rollback
  when: manual
  environment:
    name: evolution
    url: https://evolution-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

2PRSN:install:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=presentation --image=devdocker.infra.kube/cryptopay/database-presentation --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --install
  when: manual
  environment:
    name: presentation
    url: https://presentation-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

2PRSN:rollback:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: rollback
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=presentation --image=devdocker.infra.kube/cryptopay/database-presentation --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --rollback
  when: manual
  environment:
    name: presentation
    url: https://presentation-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

3UAT:install:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=preproduction --image=devdocker.infra.kube/cryptopay/database-preproduction --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --install
  when: manual
  environment:
    name: preproduction
    url: https://preproduction-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

3UAT:rollback:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: rollback
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=preproduction --image=devdocker.infra.kube/cryptopay/database-preproduction --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --rollback
  when: manual
  environment:
    name: preproduction
    url: https://preproduction-cryptopay.dev.kube
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

4PROD:install:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=prod --kube-namespace=cryptopay --image=harbor.infra.kube/cryptopay/database-production --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --install
  when: manual
  environment:
    name: production
    url: https://cryptopay.band/
  tags:
    - crtpdpl
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/

4PROD:rollback:db:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: rollback
  script:
    - export KUBECONFIG=/tmp/.kube-config
    - echo "$KUBECONF_BASE64" | base64 -d > "${KUBECONFIG}"
    - ./migration/migration-exec.sh --kube-context=prod --kube-namespace=cryptopay --image=harbor.infra.kube/cryptopay/database-production --tag="$(echo $CI_COMMIT_TAG | sed 's/^DB-//g')" --rollback
  when: manual
  environment:
    name: production
    url: https://cryptopay.band/
  tags:
    - crtpdpl
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^DB-.*/
