image: node:11-alpine

.scripting: &utils |
  function setup_npm_token() {
    if [ -z "$ZXTEAM_NPMJS_ARTIFACTS_TOKEN" ]; then
      echo "ZXTEAM_NPMJS_ARTIFACTS_TOKEN variable is not defined" >&2
      exit 254
    fi
    echo "//npmjs.artifacts.zxteam.net/:_authToken=$ZXTEAM_NPMJS_ARTIFACTS_TOKEN" >> ~/.npmrc
  }
  function verify_package_version() {
    local PACKAGE_VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json)
    if [ "${PACKAGE_VERSION}" != "${CI_COMMIT_TAG}" ]; then
      echo "Wrong package version. Tag version '${CI_COMMIT_TAG}' should be equal to package version '${PACKAGE_VERSION}'"
      exit -255
    fi
  }


cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - stag
  - package

compile:
  stage: build
  tags:
    - docker
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - npm install --progress=false
  script:
    - npm run build
  artifacts:
    expire_in: 3 days
    untracked: false
    paths:
      - .build/
      - .dist/
      - node_modules/
      - src/
      - test/
      - scripts/
      - .npmrc
      - Dockerfile
      - Dockerfile.redis
      - config.ini
      - log4js.json
      - package.json
    when: on_success

test:
  stage: test
  tags:
    - docker
  dependencies:
    - compile
  variables:
    GIT_STRATEGY: none
    DATASTORAGE_URL: 'redis://devtest@redis:6379/5'
  services:
    - name: redis
      alias: redis
  script:
    - npm run test

container:tag:
  stage: stag
  tags:
    - docker-builder
  dependencies:
    - compile
    - test
  when: on_success
  only:
    - tags
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest . -f Dockerfile.redis
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} -> ${CI_REGISTRY_IMAGE}:latest was staged successfully"

mix:tag:
  stage: stag
  tags:
    - docker-builder
  dependencies:
    - compile
    - test
  when: manual
  only:
    - branches
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest . -f Dockerfile.redis
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} -> ${CI_REGISTRY_IMAGE}:latest was staged successfully"

image:commit:
  stage: stag
  dependencies:
    - compile
  tags:
    - docker-builder
  when: manual
  only:
    - branches
  variables:
    GIT_STRATEGY: clone
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - docker build --tag "${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)" --build-arg TARGET="${CI_COMMIT_REF_SLUG}" --build-arg IMAGE="${BUILD_IMAGE}" .
    - echo "Make image tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)"
    - docker tag "${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)"
    - echo "Make image tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    - docker tag "${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    - echo "Push image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8)"
    - echo "Push image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    - echo "Image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.$(echo ${CI_COMMIT_SHA} | head -c 8) -> ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} was staged successfully"

package:tag:
  stage: package
  tags:
    - docker
  dependencies:
    - compile
    - test
  when: manual
  only:
    - tags
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - *utils
    - verify_package_version
    - setup_npm_token
  script:
    - echo "Publish package to the npmjs.artifacts.zxteam.net registry"
    - cd .dist && cat .npmrc && npm publish
