environment: evolution

docker:
  cpservice:
    migrationImage: devdocker.infra.kube/cryptopay/cpservice-migration
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    tag: latest,
    cmd:
      [
        "--config-file=/etc/cexiolabs/cryptopay.service/service.config",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-env",
      ]
    cmdbin: "aggrless"

ingress:
  API:
    type: internal
    domain: api-evolution-cryptopay.dev.kube
    certSecretName: dev
    # API does not require client's certificate
    #backendCaSecretName:
    backendInsecure: yes
    paths:
      "/":
        backendServiceName: cpservice
        backendServicePort: 8080
  SysAdmin:
    type: internal
    domain: sysadmin-evolution-cryptopay.dev.kube
    certSecretName: dev
    backendInsecure: yes
    paths:
      "/":
        backendServiceName: cpservice
        backendServicePort: 8081
  Dashboard:
    type: internal
    domain: dashboard-evolution-cryptopay.dev.kube
    certSecretName: dev
    backendCaSecretName: ca-secret
    backendInsecure: yes
    paths:
      "/":
        backendServiceName: cpservice
        backendServicePort: 8082
  Specs:
    type: internal
    domain: evolution-cryptopay.dev.kube
    certSecretName: dev
    backendInsecure: yes
    paths:
      "/":
        backendServiceName: cpservice
        backendServicePort: 8083
      "/v2/callback/cryptoproviders/cex/":
        backendServiceName: cpservice
        backendServicePort: 8084
