{
 "title": "Cryptopay-Evolution-Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage/requested",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{namespace=\"cryptopay-evolution\",container!=\"\",container!=\"POD\"}[5m])) / sum by (container,pod)(kube_pod_container_resource_requests_cpu_cores{namespace=\"cryptopay-evolution\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM usage/limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(container_memory_working_set_bytes{namespace=\"cryptopay-evolution\",container!=\"\",container!=\"POD\"}) / sum by (container,pod)(kube_pod_container_resource_limits_memory_bytes{namespace=\"cryptopay-evolution\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing: Percent of failed requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum by (kubernetes_node)(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-evolution\", kubernetes_name=\"cryptopay-processing\", status_code=~\"[23].*\"})) / (sum by (kubernetes_node)(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-evolution\", kubernetes_name=\"cryptopay-processing\"})))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Processing: Critical errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (critical_errors{kubernetes_namespace=\"cryptopay-evolution\", kubernetes_name=\"cryptopay-processing\"})",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Processing: General errors / hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (rate(general_errors{kubernetes_namespace=\"cryptopay-evolution\", kubernetes_name=\"cryptopay-processing\"}[1h])) * 3600",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}