# kubectl --namespace cexpay-presentation-admin get --output=yaml ConfigMap/invoice-envvars
# kubectl --namespace cexpay-presentation-admin get --output=json ConfigMap/invoice-envvars | jq -r ".data" | yq eval -P | sed 's/^/  /'
# kubectl --namespace cexpay-presentation-admin apply --filename=runtime.configmaps/presentation/invoice-envvars.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-envvars
  namespace: cexpay-presentation-admin
