# kubectl --namespace cexpay-presentation-admin get --output=yaml ConfigMap/ptmerchant-envvars
# kubectl --namespace cexpay-presentation-admin get --output=json ConfigMap/ptmerchant-envvars | jq -r ".data" | yq eval -P | sed 's/^/  /'
# kubectl --namespace cexpay-presentation-admin apply --filename=runtime.configmaps/presentation/ptmerchant-envvars.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ptmerchant-envvars
  namespace: cexpay-presentation-admin
