# kubectl --namespace cexiopay-infra get --output=yaml Deployment/notifier
# kubectl --namespace cexiopay-infra apply --filename=infra/service-notifier.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: cexiopay-infra
  labels:
    workload.user.cattle.io/workloadselector: deployment-cexiopay-infra-notifier
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-cexiopay-infra-notifier
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-cexiopay-infra-notifier
    spec:
      containers:
      - env:
        - name: endpoint.subscriber.bindPath
          value: /subscriber
        image: docker.registry.zxteam.net/pub/notifier/service:master.6d36f8ce
        imagePullPolicy: IfNotPresent
        name: notifier
        ports:
        - containerPort: 8080
          name: 80tcp802
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
