# kubectl --namespace cexpay-infra get --output=yaml Deployment/redis
# kubectl --namespace cexpay-infra apply --filename=infra/deployment-redis.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cexpay-infra
  labels:
    app: redis
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9121"
        prometheus.io/scrape: "true"
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: cexpay-registry
      containers:
      - env:
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        image: docker-cexpay.infra.kube/bitnami/redis:4.0
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 9121
          name: 9121tcp0
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      - env:
        - name: REDIS_ALIAS
          value: cexpay-infra-redis
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        image: docker-cexpay.infra.kube/oliver006/redis_exporter:v1.31.4
        imagePullPolicy: Always
        name: redis-exporter
        ports:
        - containerPort: 9121
          name: 9121tcp0
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
