# kubectl --namespace cexiopay-infra get --output=yaml Deployment/rabbitmq
# kubectl --namespace cexiopay-infra apply --filename=infra/deployment-rabbitmq.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: cexiopay-infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_MNESIA_DIR
          value: /var/lib/rabbitmq/data
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: -rabbitmq_management path_prefix "rabbitmq"
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              key: rabbitmq-erlang-cookie
              name: rabbitmq
              optional: false
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: rabbitmq
              optional: false
        image: rabbitmq:3.8.14-management-alpine
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 15672
          name: management
          protocol: TCP
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pv-claim
