# kubectl --namespace cexiopay-infra get --output=yaml Ingress
# kubectl --namespace cexiopay-infra apply --filename=infra/ingress.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default
  namespace: cexiopay-infra
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/secure-backends: "false"
spec:
  tls:
  - hosts:
    - infra-cexiopay.dev.kube
    secretName: dev
  rules:
  - host: infra-cexiopay.dev.kube
    http:
      paths:
      - backend:
          serviceName: notifier
          servicePort: 8080
        path: /v2
      - backend:
          serviceName: rabbitmq
          servicePort: 15672
        path: /rabbitmq
      - backend:
          serviceName: notifier
          servicePort: 8080
        path: /subscriber

