# kubectl --namespace cexpay-infra get --output=yaml Service/postgres
# kubectl --namespace cexpay-infra apply --filename=infra/service-postgres.yaml

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cexpay-infra
  labels:
    app: postgres
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: postgres
  ports:
  - name: pg
    port: 5432
    protocol: TCP
    targetPort: 5432
