# kubectl --namespace cexpay-infra get --output=yaml Service/redis
# kubectl --namespace cexpay-infra apply --filename=infra/service-redis.yaml

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cexpay-infra
  labels:
    app: redis
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
