environment: production

application:
  api:
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cexiopay.api/legacy-cpservice-config/WTF-prod.json
  identity:
    env:
      Emailer__SendGrid__senderEmail: "no-reply@cexiopay.band"

  processing:
    args:
      [
        "--config-file=/etc/cexiolabs/cexiopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup-dach.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup-goldenpay.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-production.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets-setup",
        "--config-env"
      ]

ingress:
  API:
    domain: api.cexiopay.band
    certSecretName: ingress-gate-api-dashboard
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v3/":
        backendServiceName: api
        backendServicePort: 8443
  API-Internal:
    domain: api-cexiopay.prodcryptopay.kube
    certSecretName: callback
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v3/":
        backendServiceName: api
        backendServicePort: 8443
  Callbacks:
    domain: callback.prodcryptopay.kube
    certSecretName: callback
    paths:
      "/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  DashboardObsolete:
    domain: dashboard.cexiopay.band
    certSecretName: ingress-gate-api-dashboard
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboardobsolete
        backendServicePort: 8445
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  # Gate:
  #   domain: gate.cexiopay.band
  #   certSecretName: ingress-gate-api-dashboard
  #   nginxConfigurationSnippet: |
  #     add_header Last-Modified $date_gmt;
  #     add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
  #     if_modified_since off;
  #     expires off;
  #     etag off;
  #   paths:
  #     "/":
  #       backendServiceName: gateuiserve
  #       backendServicePort: 8080
  #     "/v2/gate/":
  #       backendServiceName: processing
  #       backendServicePort: 8085
  #     "/v2/gate-callback/":
  #       backendServiceName: processing
  #       backendServicePort: 8085
  Identity:
    domain: id.cexiopay.band
    certSecretName: ingress-gate-api-dashboard
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443
  MessengerBridge:
    # THIS temporary endpoint just for testing purposes
    domain: messengerbridge-cexiopay.prodcryptopay.kube
    certSecretName: callback
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
