zone: evolution

application:

  api:
    serviceImage: harbor.infra.kube/cexpay/api/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.api/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.api/appsettings.evolution.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.api/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id-evolution-cexpay.dev.kube
      WTFProviderConfigurationFile: /etc/cexiolabs/cexpay.api/legacy-cpservice-config/WTF-dev.json

  board:
    serviceImage: harbor.infra.kube/cexpay/board/snapshot/amd64
    env:
      API_SERVICE_URL: https://api-evolution-cexpay.dev.kube
      IDENTITY_SERVICE_URL: https://id-evolution-cexpay.dev.kube

  gatehostinternal:
    serviceImage: harbor.infra.kube/cexpay/gate/hostinternal/snapshot/amd64
    env:
      GATE_BASE_URL: https://gate-evolution-cexpay.dev.kube

  gateintegrationdemo:
    env:
      GATE_URL: https://gate-evolution-cexpay.dev.kube

  identity:
    serviceImage: harbor.infra.kube/cexpay/identity/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.identity/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.identity/appsettings.evolution.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.identity/secrets",
        "--config-env",
        "--log-json"
      ]

  invoice:
    serviceImage: harbor.infra.kube/cexpay/invoice/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.invoice/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.invoice/appsettings.evolution.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.invoice/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id-evolution-cexpay.dev.kube

  landing:
    serviceImage: docker-cexpay.infra.kube/cexpay/landing/snapshot/amd64

  notifier:
    serviceImage: harbor.infra.kube/cexiolabs/communitysoft/notifier/csharp/snapshot/amd64

  processing:
    serviceImage: harbor.infra.kube/cexpay/processing/snapshot/amd64
    args:
      [
        "--config-file=/etc/cexiolabs/cexpay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service-zone-evolution.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexpay/secrets",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service"
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"


ingress:

  API:
    blue:
      domain: api-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: api
        backendServicePort: 8443
      "/emulator-crypto":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082

  Board:
    blue:
      domain: board-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: board
        backendServicePort: 8443

  Callbacks:
    blue:
      domain: callback-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086

  Echo:
    blue:
      domain: echo-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: echo
        backendServicePort: 8443

  Gate:
    blue:
      domain: gate-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: gatehostinternal
        backendServicePort: 8443

  GateIntegrationDemo:
    blue:
      domain: gateintegrationdemo-evolution-cexpay.dev.kube
    backendInsecure: true
    paths:
      "/":
        backendServiceName: gateintegrationdemo
        backendServicePort: 8080

  Identity:
    blue:
      domain: id-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443

  Invoice:
    blue:
      domain: invoice-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: invoice
        backendServicePort: 8443

  Landing:
    blue:
      domain: evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: landing
        backendServicePort: 8443

  MessengerBridge:
    blue:
      # THIS endpoint just for development purposes
      domain: messengerbridge-evolution-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
