zone: test

application:

  api:
    serviceImage: harbor.infra.kube/cexiopay/api/snapshot
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiopay.api/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiopay.api/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiopay.api/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cexiopay.api/legacy-cpservice-config/WTF-dev.json

  dashboard:
    serviceImage: harbor.infra.kube/cexiopay/dashboard/snapshot
    replicas: 1

  dashboardlegacy2:
    serviceImage: harbor.infra.kube/cexiopay/dashboard-react/snapshot
    replicas: 1

  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://processing:8443/
      GATE_ID: d3812aab-e74e-4408-94ac-0f6029f680f6
      GATE_URL: https://gate.pay-cex-test.net
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    replicas: 0

  identity:
    serviceImage: harbor.infra.kube/cexiopay/identity/snapshot
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiopay.identity/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiopay.identity/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiopay.identity/secrets",
        "--config-env",
        "--log-json"
      ]

  messengerbridge:
    replicas: 0

  processing:
    serviceImage: harbor.infra.kube/cexiopay/processing/snapshot
    args:
      [
        "--config-file=/etc/cexiolabs/cexiopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-zone-test.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service"
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate.pay-cex-test.net


ingress:

  blue:

    API:
      domain: api.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
      backendInsecure: false
      nginxConfigurationSnippet: |
        rewrite ^/$ /v2/time redirect;
      paths:
        "/":
          backendServiceName: api
          backendServicePort: 8443
        "/emulator-crypto":
          backendServiceName: processing
          backendServicePort: 8080
        "/v2/":
          backendServiceName: processing
          backendServicePort: 8080

    Callbacks:
      # TEMPORARY USE presentation REGARDS TO WTF2 CALLBACKS CONFIGURATION
      domain: callback-presentation-cexiopay.dev.kube
      certSecretName: dev
      paths:
        "/ws/":
          backendServiceName: processing
          backendServicePort: 8086

    DashboardLegacy2:
      domain: dashboard-testnet.cryptopay.band
      certSecretName: cryptopay-band
      nginxConfigurationSnippet: |
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      paths:
        "/":
          backendServiceName: dashboardlegacy2
          backendServicePort: 8445
        "/v2/dashboard/":
          backendServiceName: processing
          backendServicePort: 8082

    Echo:
      domain: echo.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
      backendInsecure: false
      paths:
        "/":
          backendServiceName: echo
          backendServicePort: 8443

    Gate:
      domain: gate.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
      backendInsecure: false
      nginxConfigurationSnippet: |
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      paths:
        "/":
          backendServiceName: processing
          backendServicePort: 8085

    Identity:
      domain: id.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
      backendInsecure: false
      paths:
        "/":
          backendServiceName: identity
          backendServicePort: 8443

    MessengerBridge:
      # THIS endpoint just for development purposes
      domain: messengerbridge-test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      paths:
        "/":
          backendServiceName: messengerbridge
          backendServicePort: 8443

    Welcome:
      domain: pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
      backendInsecure: false
      paths:
        "/":
          backendServiceName: processing
          backendServicePort: 8083
        "/widget-demo/":
          backendServiceName: demo
          backendServicePort: 8443

  nonblue:

    API:
      # Make final domain "api-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   api-green-test-cexiopay.dev.kube
      #   api-master-test-cexiopay.dev.kube
      domainPerfix: api-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      nginxConfigurationSnippet: |
        rewrite ^/$ /v2/time redirect;
      paths:
        "/":
          backendServiceName: api
          backendServicePort: 8443
        "/emulator-crypto":
          backendServiceName: processing
          backendServicePort: 8080
        "/v2/":
          backendServiceName: processing
          backendServicePort: 8080

    Callbacks:
      # Make final domain "callback-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   callback-green-test-cexiopay.dev.kube
      #   callback-master-test-cexiopay.dev.kube
      domainPerfix: callback-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      paths:
        "/ws/":
          backendServiceName: processing
          backendServicePort: 8086

    Board:
      # Make final domain "board-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   board-green-test-cexiopay.dev.kube
      #   board-master-test-cexiopay.dev.kube
      domainPerfix: board-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      nginxConfigurationSnippet: |
        rewrite ^/$ /next/ redirect;
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      paths:
        "/legacy2/":
          backendServiceName: dashboardlegacy2
          backendServicePort: 8443
        "/v2/dashboard/":
          backendServiceName: processing
          backendServicePort: 8082
        "/next/":
          backendServiceName: dashboard
          backendServicePort: 8443

    Echo:
      # Make final domain "echo-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   echo-green-test-cexiopay.dev.kube
      #   echo-master-test-cexiopay.dev.kube
      domainPerfix: echo-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      paths:
        "/":
          backendServiceName: echo
          backendServicePort: 8443

    Gate:
      # Make final domain "gate-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   gate-green-test-cexiopay.dev.kube
      #   gate-master-test-cexiopay.dev.kube
      domainPerfix: gate-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      nginxConfigurationSnippet: |
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      paths:
        "/":
          backendServiceName: processing
          backendServicePort: 8085

    Identity:
      # Make final domain "id-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   id-green-test-cexiopay.dev.kube
      #   id-master-test-cexiopay.dev.kube
      domainPerfix: id-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      paths:
        "/":
          backendServiceName: identity
          backendServicePort: 8443

    MessengerBridge:
      # THIS endpoint just for development purposes
      # Make final domain "messengerbridge-<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   messengerbridge-green-test-cexiopay.dev.kube
      #   messengerbridge-master-test-cexiopay.dev.kube
      domainPerfix: messengerbridge-
      domainSuffix: -test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      paths:
        "/":
          backendServiceName: messengerbridge
          backendServicePort: 8443

    Welcome:
      # Make final domain "<HelmReleaseName>-test-cexiopay.dev.kube" like a:
      #   green-test-cexiopay.dev.kube
      #   master-test-cexiopay.dev.kube
      domainPerfix: ""
      domainSuffix: test-cexiopay.dev.kube
      certSecretName: dev
      backendInsecure: false
      paths:
        "/":
          backendServiceName: processing
          backendServicePort: 8083
        "/widget-demo/":
          backendServiceName: demo
          backendServicePort: 8443
