environment: production

application:
  processing:
    tag: 2.0.4
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-production.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
      ]
    replicas: 1
  dashboardserve:
    serviceImage: cexiolabs/http-https-echo
    tag: latest
    env:
      SSL_CERT_FILE: /etc/cexiolabs/cryptopay/ssl/tls.crt
      SSL_KEY_FILE: /etc/cexiolabs/cryptopay/ssl/tls.key
      HTTPS_PORT: 8080
  gateuiserve:
    serviceImage: cexiolabs/http-https-echo
    tag: latest
    env:
      SSL_CERT_FILE: /etc/cexiolabs/cryptopay/ssl/tls.crt
      SSL_KEY_FILE: /etc/cexiolabs/cryptopay/ssl/tls.key
      HTTPS_PORT: 8080

ingress:
  API:
    type: external
    domain: api.cryptopay.band
    certSecretName: ingress-gate-api-dashboard
    # API does not require client's certificate
    #backendCaSecretName:
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard:
    type: external
    domain: dashboard.cryptopay.band
    certSecretName: ingress-gate-api-dashboard
    # Dashboard does not require client's certificate
    #backendCaSecretName:
    paths:
      "/":
        backendServiceName: dashboardserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8080
  Gateway:
    type: external
    domain: gate.cryptopay.band
    certSecretName: ingress-gate-api-dashboard
    # Gateway does not require client's certificate
    #backendCaSecretName:
    paths:
      "/":
        backendServiceName: gateuiserve
        backendServicePort: 8080
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Wtf2PssCallbacks:
    type: internal
    domain: callback.prodcryptopay.kube
    certSecretName: callback
    # Gateway does not require client's certificate
    #backendCaSecretName:
    paths:
      "/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8080
