environment: presentation

docker:
  processing:
    #serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    serviceImage: cexiolabs/http-https-echo
    tag: latest
    # args:
    #   [
    #     "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
    #     "--config-file=/etc/cexiolabs/cryptopay.processing/gateway.config",
    #     "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
    #     "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
    #     "--config-env",
    #   ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      SSL_CERT_FILE: /etc/cexiolabs/cryptopay/ssl/tls.crt
      SSL_KEY_FILE: /etc/cexiolabs/cryptopay/ssl/tls.key
      HTTPS_PORT: 8080
  dashboardserve:
    # serviceImage: devdocker.infra.kube/cryptopay/dashboard
    serviceImage: cexiolabs/http-https-echo
    tag: latest
    env:
      SSL_CERT_FILE: /etc/cexiolabs/cryptopay/ssl/tls.crt
      SSL_KEY_FILE: /etc/cexiolabs/cryptopay/ssl/tls.key
      HTTPS_PORT: 8080
  gatewayserve:
    # serviceImage: harbor.infra.kube/cryptopay/gateway
    serviceImage: cexiolabs/http-https-echo
    tag: latest
    env:
      SSL_CERT_FILE: /etc/cexiolabs/cryptopay/ssl/tls.crt
      SSL_KEY_FILE: /etc/cexiolabs/cryptopay/ssl/tls.key
      HTTPS_PORT: 8080
ingress:
  API-Internal:
    type: internal
    domain: api-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  API-External:
    type: external
    domain: api-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard-Internal:
    type: internal
    domain: dashboard-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: dashboardserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard-External:
    type: external
    domain: dashboard-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: dashboardserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8080
  Gateway-Internal:
    type: internal
    domain: gateway-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: gatewayserve
        backendServicePort: 8080
      "/v2/gateway/api/":
        backendServiceName: processing
        backendServicePort: 8080
  Gateway-External:
    type: external
    domain: gateway-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: gatewayserve
        backendServicePort: 8080
      "/v2/widget/":
        backendServiceName: processing
        backendServicePort: 8080
  Specs-External:
    type: external
    domain: testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  SpecsAndWtf2PssCallbacks-Internal:
    type: internal
    domain: presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/callback/cryptoproviders/":
        backendServiceName: processing
        backendServicePort: 8080
