zone: presentation

application:

  api:
    serviceImage: harbor.infra.kube/cexiopay/api/snapshot
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiopay.api/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiopay.api/appsettings.presentation.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiopay.api/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id-presentation-cexiopay.dev.kube
      WTFProviderConfigurationFile: /etc/cexiolabs/cexiopay.api/legacy-cpservice-config/WTF-dev.json
    replicas: 1

  board:
    serviceImage: harbor.infra.kube/cexiopay/board/snapshot
    replicas: 1

  dashboardlegacy2:
    serviceImage: harbor.infra.kube/cexiopay/dashboard-react/snapshot
    replicas: 1

  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://processing:8080/
      GATE_ID: 51c15da2-a79b-456d-8300-7d289bc97bc9
      GATE_URL: https://gate-testnet.cryptopay.band
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    replicas: 0

  gatehostinternal:
    serviceImage: devdocker.infra.kube/cexiopay/gate/hostinternal/snapshot
    replicas: 0

  identity:
    serviceImage: harbor.infra.kube/cexiopay/identity/snapshot
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiopay.identity/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiopay.identity/appsettings.presentation.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiopay.identity/secrets",
        "--config-env",
        "--log-json"
      ]
    replicas: 1

  landing:
    serviceImage: devdocker.infra.kube/cexiopay/landing/snapshot
    replicas: 1

  notifier:
    serviceImage: harbor.infra.kube/cexiolabs/communitysoft/notifier/csharp/snapshot
    replicas: 1

  processing:
    serviceImage: harbor.infra.kube/cexiopay/processing/snapshot
    args:
      [
        "--config-file=/etc/cexiolabs/cexiopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-presentation.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate-presentation-cexiopay.dev.kube
    replicas: 0


ingress:

  API:
    blue:
      domain: api-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: api
        backendServicePort: 8443
      "/v2/":
        backendServiceName: processing
        backendServicePort: 8080

  Board:
    blue:
      domain: board-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: board
        backendServicePort: 8443

  Callbacks:
    blue:
      domain: callback-presentation-cexiopay.dev.kube
      certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086

  Dashboard:
    blue:
      domain: dashboard-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboardlegacy2
        backendServicePort: 8443
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082

  Echo:
    blue:
      domain: echo-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: echo
        backendServicePort: 8443

  Gate:
    blue:
      domain: gate-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8085

  Gatehostinternal:
    blue:
      domain: gate3-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: gatehostinternal
        backendServicePort: 8443

  Gatehostinternal:
    blue:
      domain: gate3-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: gatehostinternal
        backendServicePort: 8443

  Identity:
    blue:
      domain: id-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443

  Landing:
    blue:
      domain: presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: landing
        backendServicePort: 8443
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8443

  MessengerBridge:
    blue:
      # THIS endpoint just for development purposes
      domain: messengerbridge-presentation-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
