environment: presentation

docker:
  processing:
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    tag: latest
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-file=/etc/cexiolabs/cryptopay.processing/gateway.config",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
      ]
    cmdbin: "aggrless"
    debugPort: 9229
  dashboard:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard
    tag: latest

ingress:
  API-Internal:
    type: internal
    domain: api-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  API-External:
    type: external
    domain: api-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard-Internal:
    type: internal
    domain: dashboard-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: dashboard
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Dashboard-External:
    type: external
    domain: dashboard-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: dashboard
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  SpecsAndWidgetAndGateway-External:
    type: external
    domain: testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/v2/gateway/api/":
        backendServiceName: processing
        backendServicePort: 8080
      "/widget/":
        backendServiceName: processing
        backendServicePort: 8086
  SpecsAndWidgetAndGatewayAndWtf2PssCallbacks-Internal:
    type: internal
    domain: presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/v2/gateway/api/":
        backendServiceName: processing
        backendServicePort: 8082
      "/v2/callback/cryptoproviders/cex/wtf2pss/":
        backendServiceName: processing
        backendServicePort: 8084
      "/widget/":
        backendServiceName: processing
        backendServicePort: 8086
