zone: test

application:

  processingapi:
    serviceImage: harbor.infra.kube/cexpay/api/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.api/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.api/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.api/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id.pay-cex-test.net
      WTFProviderConfigurationFile: /etc/cexiolabs/cexpay.api/legacy-cpservice-config/WTF-dev.json

  board:
    serviceImage: harbor.infra.kube/cexpay/board/snapshot/amd64
    env:
      CEXPAY_GATEWAY_ORIGIN_WHITE_LIST: |
        ["board.pay-cex-test.net"]
      CEXPAY_IDENTITY_API_URL: https://id.pay-cex-test.net
      CEXPAY_INVOICE_API_URL: https://invoice.pay-cex-test.net
      CEXPAY_PAYTOOLS_INVOICE_API_URL: https://api.pay-cex-test.net/paytools/v1/invoice
      CEXPAY_PROCESSING_V2_API_URL: https://api.pay-cex-test.net/v2
      CEXPAY_PROCESSING_V3_API_URL: https://api.pay-cex-test.net/v3
      OAUTH_CLIENT_ID: CEXPay.Board
      OAUTH_CALLBACK_PATH: /profile/oauth-challenge/
      POST_LOGOUT_REDIRECT_URL: https://www.cexpay.io

  gatehostinternal:
    serviceImage: harbor.infra.kube/cexpay/gate/hostinternal/snapshot/amd64
    env:
      GATE_BASE_URL: https://gate.pay-cex-test.net

  gateintegrationdemo:
    env:
      GATE_URL: https://gate.pay-cex-test.net
      GATE_CA_FILE: /etc/cexiolabs/cexpay/InfraWNBCA.crt

  identity:
    serviceImage: harbor.infra.kube/cexpay/identity/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.identity/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.identity/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.identity/secrets",
        "--config-env",
        "--log-json"
      ]

  invoice:
    serviceImage: harbor.infra.kube/cexpay/invoice/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.invoice/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.invoice/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.invoice/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id.pay-cex-test.net

  landing:
    serviceImage: docker-cexpay.infra.kube/cexpay/landing/snapshot/amd64

  notifier:
    serviceImage: harbor.infra.kube/cexiolabs/communitysoft/notifier/csharp/snapshot/amd64

  processing:
    serviceImage: harbor.infra.kube/cexpay/processing/snapshot/amd64
    args:
      [
        "--config-file=/etc/cexiolabs/cexpay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service-zone-test.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexpay/secrets",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service"
      ]
    env:
      CMDBIN: "snapshot"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"

  ptinvoice:
    serviceImage: harbor.infra.kube/cexpay/paytools/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.paytools/CEXPay.PaymentTools.InvoiceAPI/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.paytools/CEXPay.PaymentTools.InvoiceAPI/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.paytools/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id.pay-cex-test.net

  ptservice:
    serviceImage: harbor.infra.kube/cexpay/paytools/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.paytools/CEXPay.PaymentTools.InvoiceService/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.paytools/CEXPay.PaymentTools.InvoiceService/appsettings.test.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.paytools/secrets",
        "--config-env",
        "--log-json"
      ]
  env:
    IdentityServerAuthentication__ValidIssuers: https://id-evolution-cexpay.dev.kube

  statuspage:
    serviceImage: harbor.infra.kube/cexpay/statuspage/snapshot/amd64
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiolabs.statuspage.host/StatusPage.AppHost/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiolabs.statuspage.host/StatusPage.AppHost/appsettings.test.json",
        "--config-json-file=/etc/cexiolabs/cexpay.statuspage/checkers-configuration.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiolabs.statuspage.host/secrets",
        "--config-env",
        "--log-json"
      ]
    replicas: 0

  supportbot:
    env:
      CEXPAY_API_CA_CERTIFICATE_FILE: /etc/cexiolabs/cexpay/trusted-ca.crt

ingress:

  API:
    blue:
      domain: api.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "api-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   api-green-test-cexpay.dev.kube
      #   api-master-test-cexpay.dev.kube
      domainPerfix: api-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/processing/v2/":
        backendServiceName: processing
        backendServicePort: 8080
      "/processing/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
      "/processing/v3/":
        backendServiceName: processingapi
        backendServicePort: 8443
      "/emulator-crypto":
        backendServiceName: processing
        backendServicePort: 8080
      "/emulator-exchange":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
      "/paytools/v1/":
        backendServiceName: ptinvoice
        backendServicePort: 8443

  Board:
    nonblue:
      # Make final domain "board-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   board-green-test-cexpay.dev.kube
      #   board-master-test-cexpay.dev.kube
      domainPerfix: board-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: board
        backendServicePort: 8443

  Callbacks:
    blue:
      domain: callback-test-cexpay.dev.kube
      certSecretName: dev
    nonblue:
      # Make final domain "callback-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   callback-green-test-cexpay.dev.kube
      #   callback-master-test-cexpay.dev.kube
      domainPerfix: callback-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/processing/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086

  Echo:
    blue:
      domain: echo.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "echo-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   echo-green-test-cexpay.dev.kube
      #   echo-master-test-cexpay.dev.kube
      domainPerfix: echo-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: echo
        backendServicePort: 8443

  Gate:
    blue:
      domain: gate.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "gate-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   gate-green-test-cexpay.dev.kube
      #   gate-master-test-cexpay.dev.kube
      domainPerfix: gate-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: gatehostinternal
        backendServicePort: 8443

  GateIntegrationDemo:
    blue:
      domain: gateintegrationdemo.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "gateintegrationdemo-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   gateintegrationdemo-green-test-cexpay.dev.kube
      #   gateintegrationdemo-master-test-cexpay.dev.kube
      domainPerfix: gateintegrationdemo-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    backendInsecure: true
    paths:
      "/":
        backendServiceName: gateintegrationdemo
        backendServicePort: 8080

  Identity:
    blue:
      domain: id.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "id-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   id-green-test-cexpay.dev.kube
      #   id-master-test-cexpay.dev.kube
      domainPerfix: id-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443

  Invoice:
    blue:
      domain: invoice.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "invoice-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   invoice-green-test-cexpay.dev.kube
      #   invoice-master-test-cexpay.dev.kube
      domainPerfix: invoice-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: invoice
        backendServicePort: 8443

  Landing:
    blue:
      domain: pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   green-test-cexpay.dev.kube
      #   master-test-cexpay.dev.kube
      domainPerfix: ""
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: landing
        backendServicePort: 8443

  MessengerBridge:
    blue:
      # THIS endpoint just for development purposes
      domain: messengerbridge-test-cexpay.dev.kube
      certSecretName: dev
    nonblue:
      # THIS endpoint just for development purposes
      # Make final domain "messengerbridge-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   messengerbridge-green-test-cexpay.dev.kube
      #   messengerbridge-master-test-cexpay.dev.kube
      domainPerfix: messengerbridge-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443

  StatusPage:
    blue:
      domain: status.pay-cex-test.net
      certSecretName: ingress-pay-cex-test-certificate
    nonblue:
      # Make final domain "status-<HelmReleaseName>-test-cexpay.dev.kube" like a:
      #   status-green-test-cexpay.dev.kube
      #   status-master-test-cexpay.dev.kube
      domainPerfix: status-
      domainSuffix: -test-cexpay.dev.kube
      certSecretName: dev
    paths:
      "/":
        backendServiceName: statuspage
        backendServicePort: 8443
