environment: evolution

application:
  processing:
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    tag: dev
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-evolution.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
    replicas: 1
  dashboarduiserve:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard-ui
    tag: master
  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_URL: https://gate-evolution-cryptopay.dev.kube/v2/gate/??????-????-????-????-??????????
      GATE_WIDGET_URL: https://gate-evolution-cryptopay.dev.kube/??????-????-????-????-??????????
      GATE_API_PASSPHRASE: ?????
      GATE_API_SECRET: ?????
  gateuiserve:
    serviceImage: devdocker.infra.kube/cryptopay/gate-ui
    tag: master

ingress:
  API:
    type: internal
    domain: api-evolution-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard:
    type: internal
    domain: dashboard-evolution-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboarduiserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Gate:
    type: internal
    domain: gate-evolution-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: gateuiserve
        backendServicePort: 8080
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Callbacks:
    type: internal
    domain: callback-evolution-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  Specs:
    type: internal
    domain: evolution-cryptopay.dev.kube
    backendInsecure: true
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8080
