environment: evolution

application:
  dashboard:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard-backend-evolution
    # tag: master
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cryptopay.dashboard/legacy-cpservice-config/WTF-dev.json
  identity:
    serviceImage: devdocker.infra.kube/cryptopay/identity
    # tag: master
  processing:
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    # tag: master
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup-dach.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup-goldenpay.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-evolution.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate-evolution-cryptopay.dev.kube/widget
    replicas: 1
  demo:
    # tag: master
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://cryptopay-processing:8080
      GATE_ID: 09635610-6109-4179-833b-8675fa709d9b
      GATE_URL: https://gate-evolution-cryptopay.dev.kube/widget
      NODE_TLS_REJECT_UNAUTHORIZED: 0

ingress:
  API:
    type: internal
    domain: api-evolution-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard:
    type: internal
    domain: dashboard-evolution-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboard
        backendServicePort: 8445
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Gate:
    type: internal
    domain: gate-evolution-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Identity:
    type: internal
    domain: id-evolution-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443
  Callbacks:
    type: internal
    domain: callback-evolution-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  Specs:
    type: internal
    domain: evolution-cryptopay.dev.kube
    backendInsecure: true
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8080
