environment: production

application:
  processing:
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-production.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env"
#        "--runtime-gate-email-sender=nodemailer"
      ]
  echo:
    serviceImage: cexiolabs/http-https-echo
    tag: latest
    env:
      HTTPS_PORT: 8080
      LOG_LEVEL: "info"
      SSL_CERT_FILE: /etc/cexiolabs/cryptopay/ssl/tls.crt
      SSL_KEY_FILE: /etc/cexiolabs/cryptopay/ssl/tls.key

ingress:
  API:
    type: external
    domain: api.cryptopay.band
    certSecretName: ingress-gate-api-dashboard
    # API does not require client's certificate
    #backendCaSecretName:
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard:
    type: external
    domain: dashboard.cryptopay.band
    certSecretName: ingress-gate-api-dashboard
    # Dashboard does not require client's certificate
    #backendCaSecretName:
    paths:
      "/":
        backendServiceName: dashboarduiserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Gateway:
    type: external
    domain: gate.cryptopay.band
    certSecretName: ingress-gate-api-dashboard
    # Gateway does not require client's certificate
    #backendCaSecretName:
    paths:
      "/":
        backendServiceName: gateuiserve
        backendServicePort: 8080
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Callbacks:
    type: internal
    domain: callback.prodcryptopay.kube
    certSecretName: callback
    # Gateway does not require client's certificate
    #backendCaSecretName:
    paths:
      "/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  MessengerBridge-Internal:
    # THIS temporary endpoint just for testing purposes
    type: internal
    domain: messengerbridge-cryptopay.prodcryptopay.kube
    certSecretName: callback
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
