environment: presentation

application:
  dashboard:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard-backend-presentation
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cryptopay.dashboard/legacy-cpservice-config/WTF-dev.json
  processing:
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-presentation.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate-testnet.cryptopay.band/widget
    replicas: 1
  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://cryptopay-processing:8080/
      GATE_ID: 51c15da2-a79b-456d-8300-7d289bc97bc9
      GATE_URL: https://gate-testnet.cryptopay.band/widget
      NODE_TLS_REJECT_UNAUTHORIZED: 0

ingress:
  API-Internal:
    type: internal
    domain: api-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  API-External:
    type: external
    domain: api-testnet.cryptopay.band
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard-External:
    type: external
    domain: dashboard-testnet.cryptopay.band
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboard
        backendServicePort: 8445
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Gateway-Internal:
    type: internal
    domain: gate-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Gateway-External:
    type: external
    domain: gate-testnet.cryptopay.band
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/widget/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Callbacks-Internal:
    type: internal
    domain: callback-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  MessengerBridge-Internal:
    # THIS endpoint just for development purposes
    type: internal
    domain: messengerbridge-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
  Specs-External:
    type: external
    domain: testnet.cryptopay.band
    backendInsecure: true
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8080
  Specs-Internal:
    type: internal
    domain: presentation-cryptopay.dev.kube
    backendInsecure: true
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8080
