environment: presentation

application:
  processing:
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-presentation.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
    replicas: 1
  dashboarduiserve:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard-ui
  gateuiserve:
    serviceImage: devdocker.infra.kube/cryptopay/gate-ui
    tag: master

ingress:
  API-Internal:
    type: internal
    domain: api-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  API-External:
    type: external
    domain: api-testnet.cryptopay.band
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard-Internal:
    type: internal
    domain: dashboard-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboarduiserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Dashboard-External:
    type: external
    domain: dashboard-testnet.cryptopay.band
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboarduiserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Gateway-Internal:
    type: internal
    domain: gate-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: gateuiserve
        backendServicePort: 8080
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Gateway-External:
    type: external
    domain: gate-testnet.cryptopay.band
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: gateuiserve
        backendServicePort: 8080
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Specs-External:
    type: external
    domain: testnet.cryptopay.band
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
  Specs-Internal:
    type: internal
    domain: presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
