environment: presentation

docker:
  processing:
    serviceImage: devdocker.infra.kube/cryptopay/cpservice-devel
    tag: dev.3ab5a9b5
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
  dashboardserve:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard
    tag: master.76ccdc35
  gatewayserve:
    serviceImage: devdocker.infra.kube/cryptopay/payment-widget
    tag: master.58f7dc13
ingress:
  API-Internal:
    type: internal
    domain: api-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  API-External:
    type: external
    domain: api-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
  Dashboard-Internal:
    type: internal
    domain: dashboard-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: dashboardserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Dashboard-External:
    type: external
    domain: dashboard-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: dashboardserve
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Gateway-Internal:
    type: internal
    domain: gateway-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: gatewayserve
        backendServicePort: 8080
      "/v2/gateway/api/":
        backendServiceName: processing
        backendServicePort: 8085
  Gateway-External:
    type: external
    domain: gateway-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: gatewayserve
        backendServicePort: 8080
      "/v2/gateway/api/":
        backendServiceName: processing
        backendServicePort: 8085
  Specs-External:
    type: external
    domain: testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
  SpecsAndWtf2PssCallbacks-Internal:
    type: internal
    domain: presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/v2/callback/cryptoproviders/":
        backendServiceName: processing
        backendServicePort: 8084
