zone: production

application:

  processingapi:
    env:
      IdentityServerAuthentication__ValidIssuers: https://id.cexpay.io
      WTFProviderConfigurationFile: /etc/cexiolabs/cexpay.processingapi/legacy-cpservice-config/WTF-prod.json

  board:
    env:
      CEXPAY_GATEWAY_ORIGIN_WHITE_LIST: |
        ["board.cexpay.io"]
      CEXPAY_IDENTITY_API_URL: https://id.cexpay.io
      CEXPAY_INVOICE_API_URL: https://invoice.cexpay.io
      CEXPAY_PAYTOOLS_INVOICE_API_URL: https://api.cexpay.io/paytools/v1/invoice
      CEXPAY_PROCESSING_V2_API_URL: https://api.cexpay.io/v2
      CEXPAY_PROCESSING_V3_API_URL: https://api.cexpay.io/v3
      OAUTH_CLIENT_ID: CEXPay.Board
      OAUTH_CALLBACK_PATH: /profile/oauth-challenge/
      POST_LOGOUT_REDIRECT_URL: https://www.cexpay.io

  gatehostinternal:
    env:
      GATE_BASE_URL: https://gate.cexpay.io

  identity:
    env:
      Authentication__indexer: ""
      DeploymentOpts__AccountApiEndpointUrl: "https://id.cexpay.io/account/"
      Emailer__SendGrid__senderEmail: "no-reply-identity@cexpay.io"

  invoice:
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.invoice/appsettings.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.invoice/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      CorsOrigins__0: "https://board.cexpay.io"
      Emailer__SendGrid__senderEmail: "no-reply-invoice@cexpay.io"
      IdentityServerAuthentication__ValidIssuers: https://id.cexpay.io

  processing:
    args:
      [
        "--config-file=/etc/cexiolabs/cexpay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexpay.processing/service-zone-production.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexpay/secrets",
        "--config-env"
      ]
    env:
      # setup.createCryptoWallet_indexer: ""
      setup.createExchange_indexer: ""
      setup.setMissingDepositTransaction_indexer: ""
      setup.setMissingWithdrawalTransaction_indexer: ""
      setup.subscribeNotification_indexer: ""

  ptinvoice:
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.paytools/CEXPay.PaymentTools.InvoiceAPI/appsettings.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.paytools/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      IdentityServerAuthentication__ValidIssuers: https://id.cexpay.io

  ptservice:
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexpay.paytools/CEXPay.PaymentTools.InvoiceService/appsettings.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexpay.paytools/secrets",
        "--config-env",
        "--log-json"
      ]

  statuspage:
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiolabs.statuspage.host/StatusPage.AppHost/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexpay.statuspage/checkers-configuration.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiolabs.statuspage.host/secrets",
        "--config-env",
        "--log-json"
      ]

ingress:

  API:
    blue:
      domain: api.cexpay.io
      certSecretName: ingress-cexpayio-certificate
    paths:
      "/processing/v2/":
        backendServiceName: processing
        backendServicePort: 8080
      "/processing/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
      "/processing/v3/":
        backendServiceName: processingapi
        backendServicePort: 8443
      "/v2/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
      "/paytools/v1/":
        backendServiceName: ptinvoice
        backendServicePort: 8443

  API-Internal:
    blue:
      domain: api.prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    nonblue:
      # Make final domain "api-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   api-green.prod.cexpay.internal
      domainPerfix: api-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: processingapiapi
        backendServicePort: 8443
      "/v2/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082

  Board-Internal:
    nonblue:
      # Make final domain "board-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   board-green.prod.cexpay.internal
      domainPerfix: board-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: board
        backendServicePort: 8443

  Callbacks-Internal:
    blue:
      domain: callback.prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/processing/v2/callback/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086

  Callbacks-Internal-Obsolete:
    blue:
      domain: callback.prodcryptopay.kube
      certSecretName: wildcard-prodcryptopay-kube
    paths:
      "/processing/v2/callback/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/v2/callback/cryptoproviders/pss-provider-wtf2/":
        backendServiceName: processing
        backendServicePort: 8084
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086

  Gate:
    blue:
      domain: gate.cexpay.io
      certSecretName: ingress-cexpayio-certificate
    nonblue:
      # Make final domain "gate-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   gate-green.prod.cexpay.internal
      domainPerfix: gate-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: gatehostinternal
        backendServicePort: 8443

  Identity:
    blue:
      domain: id.cexpay.io
      certSecretName: ingress-cexpayio-certificate
    nonblue:
      # Make final domain "id-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   id-green.prod.cexpay.internal
      domainPerfix: id-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443

  # Identity-Obsolete-1:
  #   blue:
  #     domain: id.pay-cex.io
  #     certSecretName: ingress-pay-cex-certificate
  #   paths:
  #     "/":
  #       backendServiceName: identity
  #       backendServicePort: 8443

  Invoice:
    blue:
      domain: invoice.cexpay.io
      certSecretName: ingress-cexpayio-certificate
    nonblue:
      # Make final domain "invoice-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   invoice-green.prod.cexpay.internal
      domainPerfix: invoice-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: invoice
        backendServicePort: 8443

  MessengerBridge-Internal:
    # THIS temporary endpoint just for testing purposes
    blue:
      domain: messengerbridge.prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    nonblue:
      # Make final domain "messengerbridge-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   messengerbridge-green.prod.cexpay.internal
      domainPerfix: messengerbridge-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443

  # StatusPage:
  #   blue:
  #     domain: status.cexpay.io
  #     certSecretName: ingress-cexpayio-certificate
  #   paths:
  #     "/":
  #       backendServiceName: statuspage
  #       backendServicePort: 8443

  StatusPage-Internal:
    blue:
      domain: status.prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    nonblue:
      # Make final domain "status-<HelmReleaseName>.prod.cexpay.internal" like a:
      #   status-green.prod.cexpay.internal
      domainPerfix: status-
      domainSuffix: .prod.cexpay.internal
      certSecretName: wildcard-prod-cexpay-internal
    paths:
      "/":
        backendServiceName: statuspage
        backendServicePort: 8443

  StatusPage-Internal-Obsolete:
    blue:
      domain: status.prodcryptopay.kube
      certSecretName: wildcard-prodcryptopay-kube
    nonblue:
      # Make final domain "status-<HelmReleaseName>.prodcryptopay.kube" like a:
      #   status-green.prodcryptopay.kube
      domainPerfix: status-
      domainSuffix: .prodcryptopay.kube
      certSecretName: wildcard-prodcryptopay-kube
    paths:
      "/":
        backendServiceName: statuspage
        backendServicePort: 8443
