zone: evolution

application:

  api:
    serviceImage: harbor.infra.kube/cexiopay/api/snapshot
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiopay.api/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiopay.api/appsettings.evolution.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiopay.api/secrets",
        "--config-env",
        "--log-json"
      ]
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cexiopay.api/legacy-cpservice-config/WTF-dev.json
    replicas: 1

  board:
    serviceImage: harbor.infra.kube/cexiopay/board/snapshot
    replicas: 1

  dashboardlegacy2:
    serviceImage: harbor.infra.kube/cexiopay/dashboard-react/snapshot
    replicas: 1

  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://processing:8443
      GATE_ID: 09635610-6109-4179-833b-8675fa709d9b
      GATE_URL: https://gate-evolution-cexiopay.dev.kube
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    replicas: 0

  identity:
    serviceImage: devdocker.infra.kube/cexiopay/identity/snapshot
    args:
      [
        "--config-json-file=/etc/cexiolabs/cexiopay.identity/appsettings.json",
        "--config-json-file=/etc/cexiolabs/cexiopay.identity/appsettings.evolution.json",
        "--config-keyperfile-directory=/etc/cexiolabs/cexiopay.identity/secrets",
        "--config-env",
        "--log-json"
      ]
    replicas: 1

  notifier:
    serviceImage: devdocker.infra.kube/cexiolabs/communitysoft/notifier/csharp/snapshot
    tag: dev.11033573
    args:
      [
        "--config-json-file=/etc/cexiolabs/communitysoft.notifier/appsettings.json",
        "--config-keyperfile-directory=/etc/cexiolabs/communitysoft.notifier/secrets",
        "--config-toml-file=/etc/cexiolabs/communitysoft.notifier/extra/setup.toml",
        "--config-env",
        "--log-json"
      ]
    replicas: 1

  processing:
    serviceImage: devdocker.infra.kube/cexiopay/processing/snapshot
    tag: dev.2e57a4f3
    args:
      [
        "--config-file=/etc/cexiolabs/cexiopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-zone-evolution.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service"
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate-evolution-cexiopay.dev.kube
    replicas: 1


ingress:

  API:
    blue:
      domain: api-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: api
        backendServicePort: 8443
      "/v2/":
        backendServiceName: processing
        backendServicePort: 8080

  Board:
    blue:
      domain: board-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: board
        backendServicePort: 8443

  Callbacks:
    blue:
      domain: callback-evolution-cexiopay.dev.kube
      certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086

  Dashboard:
    blue:
      domain: dashboard-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboardlegacy2
        backendServicePort: 8443
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082

  Echo:
    blue:
      domain: echo-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: echo
        backendServicePort: 8443

  Gate:
    blue:
      domain: gate-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8085

  Identity:
    blue:
      domain: id-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443
  MessengerBridge:
    blue:
      # THIS endpoint just for development purposes
      domain: messengerbridge-evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443

  Welcome:
    blue:
      domain: evolution-cexiopay.dev.kube
      certSecretName: dev
    backendInsecure: false
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8443
