environment: evolution

application:
  api:
    serviceImage: harbor.infra.kube/cexiopay/api/snapshot
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cexiopay.api/legacy-cpservice-config/WTF-dev.json
    replicas: 1
  dashboard:
    serviceImage: harbor.infra.kube/cexiopay/dashboard/snapshot
    replicas: 0
  dashboardobsolete:
    serviceImage: devdocker.infra.kube/cexiopay/dashboard-backup-evolution
    replicas: 0
  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://cexiopay-processing:8080
      GATE_ID: 09635610-6109-4179-833b-8675fa709d9b
      GATE_URL: https://gate-evolution-cexiopay.dev.kube/widget
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    replicas: 0
  identity:
    serviceImage: devdocker.infra.kube/cexiopay/identity
    env:
      Emailer__SendGrid__senderEmail: "no-reply@evolution-cexiopay-dev.band"
    replicas: 1
  processing:
    replicas: 0
    serviceImage: devdocker.infra.kube/cexiopay/cpservice/snapshot
    args:
      [
        "--config-file=/etc/cexiolabs/cexiopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup-dach.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-setup-goldenpay.toml",
        "--config-toml-file=/etc/cexiolabs/cexiopay.processing/service-evolution.toml",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cexiopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate-evolution-cexiopay.dev.kube/widget
    replicas: 0
ingress:
  API:
    domain: api-evolution-cexiopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v3/":
        backendServiceName: api
        backendServicePort: 8443
  Callbacks:
    domain: callback-evolution-cexiopay.dev.kube
    certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  Dashboard:
    domain: dashboard-next-evolution-cexiopay.dev.kube
    backendInsecure: true
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboard
        backendServicePort: 8080
  DashboardObsolete:
    domain: dashboard-evolution-cexiopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboardobsolete
        backendServicePort: 8445
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Echo:
    domain: echo-evolution-cexiopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: echo
        backendServicePort: 8443
  Gate:
    domain: gate-evolution-cexiopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Identity:
    domain: id-evolution-cexiopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443
  MessengerBridge:
    # THIS endpoint just for development purposes
    domain: messengerbridge-evolution-cexiopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
  Welcome:
    domain: evolution-cexiopay.dev.kube
    backendInsecure: true
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8083
      "/widget-demo/":
        backendServiceName: demo
        backendServicePort: 8080
