environment: presentation

application:
  api:
    serviceImage: harbor.infra.kube/cryptopay/api/snapshot
    env:
      WTFProviderConfigurationFile: /etc/cexiolabs/cryptopay.api/legacy-cpservice-config/WTF-dev.json
      IdentityServerAuthenticationBearerAuthority: https://id-testnet.cryptopay.band
      CorsOrigins__0: https://cexiolabs.github.io
  dashboard:
    serviceImage: harbor.infra.kube/cryptopay/dashboard/snapshot
    replicas: 0
  dashboardobsolete:
    serviceImage: devdocker.infra.kube/cryptopay/dashboard-backup-presentation
    tag: 2-1-26-hotfixf16edc3d
  demo:
    env:
      BASE_PATH: /widget-demo/
      GATE_API_ORIGIN: https://cryptopay-processing:8080/
      GATE_ID: 51c15da2-a79b-456d-8300-7d289bc97bc9
      GATE_URL: https://gate-testnet.cryptopay.band/widget
      NODE_TLS_REJECT_UNAUTHORIZED: 0
  identity:
    serviceImage: harbor.infra.kube/cryptopay/identity/snapshot
    env:
      Emailer__SendGrid__senderEmail: "no-reply@presentation-cryptopay-dev.band"
  processing:
    serviceImage: harbor.infra.kube/cryptopay/cpservice/snapshot
    args:
      [
        "--config-file=/etc/cexiolabs/cryptopay.processing/service.config",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup-dach.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-setup-goldenpay.toml",
        "--config-toml-file=/etc/cexiolabs/cryptopay.processing/service-presentation.toml",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets",
        "--config-secrets-dir=/etc/cexiolabs/cryptopay/secrets-setup",
        "--config-env",
        "--runtime-gate-email-sender=nodemailer",
        "--runtime-use-notifier-service",
      ]
    env:
      CMDBIN: "devel"
      DEBUG_PORT: 9229
      DEBUG_WAIT: "no"
      LOG_LEVEL: "debug"
      GATE_URL: https://gate-presentation-cryptopay.dev.kube/widget

ingress:
  API:
    domain: api-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v3/":
        backendServiceName: api
        backendServicePort: 8443
  API-External:
    domain: api-testnet.cryptopay.band
    certSecretName: cryptopay-band
    nginxConfigurationSnippet: |
      rewrite ^/$ /v2/time redirect;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8080
      "/v3/":
        backendServiceName: api
        backendServicePort: 8443
  Callbacks:
    domain: callback-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/ws/":
        backendServiceName: processing
        backendServicePort: 8086
  Dashboard:
    domain: dashboard-presentation-cryptopay.dev.kube
    backendInsecure: true
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboard
        backendServicePort: 8080
  DashboardObsolete:
    domain: dashboard-testnet.cryptopay.band
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: dashboardobsolete
        backendServicePort: 8445
      "/v2/dashboard/":
        backendServiceName: processing
        backendServicePort: 8082
  Echo:
    domain: echo-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: echo
        backendServicePort: 8443
  Gate:
    domain: gate-presentation-cryptopay.dev.kube
    certSecretName: dev
    nginxConfigurationSnippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
    paths:
      "/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate/":
        backendServiceName: processing
        backendServicePort: 8085
      "/v2/gate-callback/":
        backendServiceName: processing
        backendServicePort: 8085
  Identity:
    domain: id-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443
  Identity-External:
    domain: id-testnet.cryptopay.band
    certSecretName: cryptopay-band
    paths:
      "/":
        backendServiceName: identity
        backendServicePort: 8443
  MessengerBridge:
    # THIS endpoint just for development purposes
    domain: messengerbridge-presentation-cryptopay.dev.kube
    certSecretName: dev
    paths:
      "/":
        backendServiceName: messengerbridge
        backendServicePort: 8443
  # Welcome:
  #   domain: presentation-cryptopay.dev.kube
  #   backendInsecure: true
  #   paths:
  #     "/":
  #       backendServiceName: processing
  #       backendServicePort: 8083
  #     "/widget-demo/":
  #       backendServiceName: demo
  #       backendServicePort: 8080
  # Welcome-External:
  #   domain: testnet.cryptopay.band
  #   backendInsecure: true
  #   paths:
  #     "/":
  #       backendServiceName: processing
  #       backendServicePort: 8083
  #     "/widget-demo/":
  #       backendServiceName: demo
  #       backendServicePort: 8080
