apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  name: {{ template "prefix" . }}gatehostinternal-certificate
spec:
  secretName: {{ template "prefix" . }}gatehostinternal-certificate
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: {{ template "prefix" . }}gatehostinternal
