apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  name: {{ template "prefix" . }}notifier-files
data:
{{ .Files.Get "tmp/configmap-notifier-files.yaml" | indent 2 }}
