{{ if and (or (eq .Values.zone "production") (eq .Values.zone "test")) (eq .Release.Name "blue") }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  name: {{ template "prefix" . }}supportbot-files
data:
{{ .Files.Get "tmp/configmap-supportbot-files.yaml" | indent 2 }}
{{ end }}
