{{ if eq .Release.Name "blue" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prefix" . }}processing
  name: {{ template "prefix" . }}processing
spec:
  replicas: {{ .Values.application.processing.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ template "prefix" . }}processing
    spec:
      containers:
      - name: processing
        image: {{ .Values.application.processing.serviceImage }}:{{ .Values.application.processing.tag }}
{{- if .Values.application.processing.command }}
        command:
{{ range .Values.application.processing.command }}
        - {{ . }}
{{ end }}
{{- end }}
{{- if .Values.application.processing.args }}
        args:
{{ range .Values.application.processing.args }}
        - {{ . }}
{{ end }}
{{- end }}
        ports:
        # Main Web server
        - containerPort: 8080
          protocol: TCP
{{- if ne .Values.zone "production" }}
        # Sysadmin should not exposed outside production container
        - containerPort: 8081
          protocol: TCP
{{- end }}
        # Dashboard API Web server
        - containerPort: 8082
          protocol: TCP
{{ if or (eq .Values.zone "evolution") (eq .Values.zone "presentation") }}
        # Swagger and welcome page used in "evolution" and "presentation" only, 
        - containerPort: 8083
          protocol: TCP
{{ end }}
{{ if not (or (eq .Values.zone "evolution") (eq .Values.zone "presentation")) }}
        # In "evolution" and "presentation" we use proxy-service called "notifier", 
        # to handle callbacks via WebSocket, so we do not need this port
        - containerPort: 8084
          protocol: TCP
{{ end }}
        # Gateway API Web server
        - containerPort: 8085
          protocol: TCP
        # WS server
        - containerPort: 8086
          protocol: TCP
        # Monitoring Web server
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config-files
          mountPath: /etc/cexiolabs/cexiopay/
          readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexiopay/ssl/
          readOnly: true
        - name: secret-files
          mountPath: /etc/cexiolabs/cexiopay/secrets/
          # The service will delete all files after read its. So need write access.
          readOnly: false
        - name: secret-setup-files
          mountPath: /etc/cexiolabs/cexiopay/secrets-setup/
          # The service will delete all files after read its. So need write access.
          readOnly: false
        envFrom:
        - configMapRef:
            name: processing-envvars
        - configMapRef:
            name: processing-envvars-setup
        env:
        - name: LOG_LEVEL
          value: info
{{- if .Values.application.processing.env }}
{{ range $key, $value := .Values.application.processing.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{ end }}
{{- end }}
        # livenessProbe:
        #   httpGet:
        #     path: /livenessProbe
        #     port: 9090
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/time
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 512m
            memory: 1024Mi
          requests:
            cpu: 128m
            memory: 256Mi
      volumes:
      - name: config-files
        configMap:
          name: processing-files
      - name: secret-files
        secret:
          secretName: processing
      - name: secret-setup-files
        secret:
          secretName: processing-setup
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}processing-certificate
{{ end }}
