{{ if eq .Release.Name "blue" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prefix" . }}messengerbridge
  name: {{ template "prefix" . }}messengerbridge
spec:
  replicas: {{ .Values.application.messengerbridge.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ template "prefix" . }}messengerbridge
    spec:
      containers:
      - name: messengerbridge
        image: {{ .Values.application.messengerbridge.serviceImage }}:{{ .Values.application.messengerbridge.tag }}
{{- if .Values.application.messengerbridge.command }}
        command:
{{ range .Values.application.messengerbridge.command }}
        - {{ . }}
{{ end }}
{{- end }}
{{- if .Values.application.messengerbridge.args }}
        args:
{{ range .Values.application.messengerbridge.args }}
        - {{ . }}
{{ end }}
{{- end }}
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: messengerbridge-files
          mountPath: /etc/cexiolabs/cexiopay
          readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexiopay/ssl
          readOnly: true
        - name: secret-files
          mountPath: /etc/cexiolabs/cexiopay/secrets
          # The service will delete all files after read its. So need write access.
          readOnly: false
        env:
        - name: LOG_LEVEL
          value: info
{{- if .Values.application.messengerbridge.env }}
{{ range $key, $value := .Values.application.messengerbridge.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{ end }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 512m
            memory: 1024Mi
          requests:
            cpu: 128m
            memory: 256Mi
      volumes:
      - name: messengerbridge-files
        configMap:
          name: messengerbridge-files
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}messengerbridge-certificate
      - name: secret-files
        secret:
          secretName: messengerbridge
{{ end }}
