apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-processing{{ template "suffix" . }}
  name: {{ .Chart.Name }}-processing{{ template "suffix" . }}
spec:
  replicas: {{ .Values.application.processing.replicas | default 2 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-processing{{ template "suffix" . }}
    spec:
      # initContainers:
      # - name: migration
      #   image: {{ .Values.application.processing.migrationImage }}:{{ .Values.application.processing.tag }}
      #   volumeMounts:
      #   - name: secret-files-migration
      #     mountPath: /etc/cexiolabs/cryptopay/secrets
      #     # The service will delete all files after read its. So need write access.
      #     readOnly: false
      #   envFrom:
      #   - configMapRef:
      #       name: processing-migration-envvars
      containers:
      - name: processing
        image: {{ .Values.application.processing.serviceImage }}:{{ .Values.application.processing.tag }}
{{- if .Values.application.processing.command }}
        command:
{{ range .Values.application.processing.command }}
        - {{ . }}
{{ end }}
{{- end }}
{{- if .Values.application.processing.args }}
        args:
{{ range .Values.application.processing.args }}
        - {{ . }}
{{ end }}
{{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
{{- if ne .Values.environment "production" }}
        - containerPort: 8081
          protocol: TCP
{{- end }}
        - containerPort: 8082
          protocol: TCP
{{ if or (eq .Values.environment "evolution") (eq .Values.environment "presentation") }}
        - containerPort: 8083
          protocol: TCP
{{ end }}
{{ if not (and (eq .Release.Name "tag") (eq .Values.environment "evolution")) }}
        # In "evolution" we use proxy-service called "notifier", to handle callbacks on local workstation via WebSocket
        - containerPort: 8084
          protocol: TCP
{{ end }}
        - containerPort: 8086
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: processing-files
          mountPath: /etc/cexiolabs/cryptopay
          readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cryptopay/ssl
          readOnly: true
        - name: secret-files
          mountPath: /etc/cexiolabs/cryptopay/secrets
          # The service will delete all files after read its. So need write access.
          readOnly: false
        - name: secret-setup-files
          mountPath: /etc/cexiolabs/cryptopay/secrets-setup
          # The service will delete all files after read its. So need write access.
          readOnly: false
        envFrom:
        - configMapRef:
            name: processing-envvars
        - configMapRef:
            name: processing-envvars-setup
        env:
        - name: RUNTIME
          value: {{ .Values.environment }}
{{- if .Values.application.processing.env }}
{{ range $key, $value := .Values.application.processing.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{ end }}
{{- end }}
        # livenessProbe:
        #   httpGet:
        #     path: /livenessProbe
        #     port: 9090
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /readinessProbe
        #     port: 9090
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
{{ if and (eq .Release.Name "tag") (eq .Values.environment "evolution") }}
      - name: notifier
        image: docker.registry.zxteam.net/pub/node/notifier/service:master.85b024fb
        env:
        - name: "server.main.type"
          value: "https"
        - name: "server.main.listenPort"
          value: "8084"
        - name: "server.main.clientCertificateMode"
          value: "none"
        - name: "server.main.serverCertificate"
          value: "/etc/cexiolabs/cryptopay/ssl/tls.crt"
        - name: "server.main.serverKey"
          value: "/etc/cexiolabs/cryptopay/ssl/tls.key"
        - name: "endpoint.subscriber.bindPath"
          value: "/v2/callback/cryptoproviders/pss-provider-wtf2-subscriber"
        ports:
        - containerPort: 8084
          protocol: TCP
        volumeMounts:
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cryptopay/ssl
          readOnly: true
{{ end }}
      volumes:
      - name: processing-files
        configMap:
          name: processing-files
      - name: secret-files
        secret:
          secretName: processing
      - name: secret-setup-files
        secret:
          secretName: processing-setup
      - name: secret-certificate
        secret:
          secretName: {{ .Chart.Name }}-processing{{ template "suffix" . }}-certificate
