apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}identity
  name: {{ template "prefix" . }}identity
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}identity
  replicas: {{ .Values.application.identity.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
        cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
        cexpay.io/ci.job: {{ .Values.ci.job | quote }}
        cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
      labels:
        app: {{ template "prefix" . }}identity
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: identity
        image: {{ .Values.application.identity.serviceImage }}:{{ .Values.application.identity.tag }}
{{- if .Values.application.identity.command }}
        command:
{{- range .Values.application.identity.command }}
        - {{ . }}
{{- end }}
{{- end }}
{{- if .Values.application.identity.args }}
        args:
{{- range .Values.application.identity.args }}
        - {{ . }}
{{- end }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "prefix" . }}identity-envvars
        env:
{{- if .Values.application.identity.env }}
{{- range $key, $value := .Values.application.identity.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        - name: Serilog__MinimumLevel__Default
          value: Information
        livenessProbe:
          httpGet:
            path: /info
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /info
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 128m
            memory: 128Mi
          requests:
            cpu: 64m
            memory: 64Mi
        # # Will be available with Kubernetes 1.20
        # startupProbe:
        #   httpGet:
        #     path: /info
        #     port: 8443
        #   failureThreshold: 60
        #   periodSeconds: 5
        volumeMounts:
        # - name: config-files
        #   mountPath: /etc/cexiolabs/cexpay.identity/
        #   readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexpay.identity/ssl/
        - name: secret-files
          mountPath: /etc/cexiolabs/cexpay.identity/secrets/
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      # - name: config-files
      #   configMap:
      #     name: {{ template "prefix" . }}identity-files
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}identity-certificate
      - name: secret-files
        secret:
          secretName: {{ template "prefix" . }}identity
