apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}statuspage
  name: {{ template "prefix" . }}statuspage
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}statuspage
  replicas: {{ .Values.application.statuspage.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
        cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
        cexpay.io/ci.job: {{ .Values.ci.job | quote }}
        cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
      labels:
        app: {{ template "prefix" . }}statuspage
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: statuspage
        image: {{ .Values.application.statuspage.serviceImage }}:{{ .Values.application.statuspage.tag }}
{{- if .Values.application.statuspage.command }}
        command:
{{- range .Values.application.statuspage.command }}
        - {{ . }}
{{- end }}
{{- end }}
        args:
{{- if .Values.application.statuspage.args }}
{{- range .Values.application.statuspage.args }}
        - {{ . }}
{{- end }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "prefix" . }}statuspage-envvars
        env:
{{- if .Values.application.statuspage.env }}
{{- range $key, $value := .Values.application.statuspage.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        - name: Serilog__MinimumLevel__Default
          value: Information
        livenessProbe:
          httpGet:
            path: /info
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /info
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 128m
            memory: 128Mi
        # # Will be available with Kubernetes 1.20
        # startupProbe:
        #   httpGet:
        #     path: /info
        #     port: 8443
        #   failureThreshold: 60
        #   periodSeconds: 5
        volumeMounts:
        - name: config-files
          mountPath: /etc/cexiolabs/cexpay.statuspage/
          readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexiolabs.statuspage.host/ssl/
        - name: secret-files
          mountPath: /etc/cexiolabs/cexiolabs.statuspage.host/secrets/
      - name: local-temporary-postgres
        image: zxteamorg/devel.postgres-13:20210515
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      - name: config-files
        configMap:
          name: {{ template "prefix" . }}statuspage-files
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}statuspage-certificate
      - name: secret-files
        secret:
          secretName: {{ template "prefix" . }}statuspage
