{{ if and (or (eq .Values.zone "production") (eq .Values.zone "test")) (eq .Release.Name "blue") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}supportbot
  name: {{ template "prefix" . }}supportbot
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}supportbot
  replicas: {{ .Values.application.supportbot.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
        cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
        cexpay.io/ci.job: {{ .Values.ci.job | quote }}
        cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
      labels:
        app: {{ template "prefix" . }}supportbot
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: supportbot
        image: {{ .Values.application.supportbot.serviceImage }}:{{ .Values.application.supportbot.tag }}
{{- if .Values.application.supportbot.command }}
        command:
{{- range .Values.application.supportbot.command }}
        - {{ . }}
{{- end }}
{{- end }}
{{- if .Values.application.supportbot.args }}
        args:
{{- range .Values.application.supportbot.args }}
        - {{ . }}
{{- end }}
{{- end }}
        volumeMounts:
        - name: config-files
          mountPath: /etc/cexiolabs/cexpay/
          readOnly: true
        envFrom:
        - configMapRef:
            name: {{ template "prefix" . }}supportbot-envvars
        - secretRef:
            name: {{ template "prefix" . }}supportbot
        env:
{{- if .Values.application.supportbot.env }}
{{- range $key, $value := .Values.application.supportbot.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        resources:
          limits:
            cpu: 128m
            memory: 256Mi
          requests:
            cpu: 64m
            memory: 128Mi
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      - name: config-files
        configMap:
          name: {{ template "prefix" . }}supportbot-files
{{ end }}
