{{ if and (ne .Values.zone "production") (eq .Release.Name "blue") }}
# 1) In "production" zone, the "landing" is hosted on GitHub Pages:
# - https://github.com/cexiolabs/cexpay.landing-hosting
# 2) In non "production" zones deploy for "blue" release ONLY
# so we deploy this conditionally
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}landing
  name: {{ template "prefix" . }}landing
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}landing
  replicas: {{ .Values.application.landing.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
        cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
        cexpay.io/ci.job: {{ .Values.ci.job | quote }}
        cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
      labels:
        app: {{ template "prefix" . }}landing
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: landing
        image: {{ .Values.application.landing.serviceImage }}:{{ .Values.application.landing.tag }}
{{- if .Values.application.landing.command }}
        command:
{{- range .Values.application.landing.command }}
        - {{ . }}
{{- end }}
{{- end }}
        args:
        - "--use-ssl"
{{- if .Values.application.landing.args }}
{{- range .Values.application.landing.args }}
        - {{ . }}
{{- end }}
{{- end }}
        env:
{{- if .Values.application.landing.env }}
{{- range $key, $value := .Values.application.landing.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        - name: BASE_PATH
          value: /
        livenessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 32m
            memory: 32Mi
        volumeMounts:
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexpay.landing/ssl/
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}landing-certificate
{{ end }}
