apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "prefix" . }}messengerbridge
  name: {{ template "prefix" . }}messengerbridge
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}messengerbridge
  replicas: {{ .Values.application.messengerbridge.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ template "prefix" . }}messengerbridge
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: messengerbridge
        image: {{ .Values.application.messengerbridge.serviceImage }}:{{ .Values.application.messengerbridge.tag }}
{{- if .Values.application.messengerbridge.command }}
        command:
{{- range .Values.application.messengerbridge.command }}
        - {{ . }}
{{- end }}
{{- end }}
{{- if .Values.application.messengerbridge.args }}
        args:
{{- range .Values.application.messengerbridge.args }}
        - {{ . }}
{{- end }}
{{- end }}
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: messengerbridge-files
          mountPath: /etc/cexiolabs/cexpay
          readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexpay/ssl
          readOnly: true
        - name: secret-files
          mountPath: /etc/cexiolabs/cexpay/secrets
          # The service will delete all files after read its. So need write access.
          readOnly: false
        env:
        - name: LOG_LEVEL
          value: info
{{- if .Values.application.messengerbridge.env }}
{{- range $key, $value := .Values.application.messengerbridge.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 512m
            memory: 1024Mi
          requests:
            cpu: 128m
            memory: 256Mi
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      - name: messengerbridge-files
        configMap:
          name: {{ template "prefix" . }}messengerbridge-files
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}messengerbridge-certificate
      - name: secret-files
        secret:
          secretName: {{ template "prefix" . }}messengerbridge
