apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-gateuiserve{{ template "suffix" . }}
  name: {{ .Chart.Name }}-gateuiserve{{ template "suffix" . }}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-gateuiserve{{ template "suffix" . }}
    spec:
      containers:
      - name: gateuiserve
        image: {{ .Values.docker.gateuiserve.serviceImage }}:{{ .Values.docker.gateuiserve.tag }}
{{- if .Values.docker.gateuiserve.command }}
        command:
{{ range .Values.docker.gateuiserve.command }}
        - {{ . }}
{{ end }}
{{- end }}
{{- if .Values.docker.gateuiserve.args }}
        args:
{{ range .Values.docker.gateuiserve.args }}
        - {{ . }}
{{ end }}
{{- end }}
        volumeMounts:
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cryptopay/ssl
          readOnly: true
        env:
        - name: RUNTIME
          value: {{ .Values.environment }}
{{- if .Values.docker.gateuiserve.env }}
{{ range $key, $value := .Values.docker.gateuiserve.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{ end }}
{{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /livenessProbe
        #     port: 9090
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /readinessProbe
        #     port: 9090
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
      volumes:
      - name: secret-certificate
        secret:
          secretName: {{ .Chart.Name }}-gateuiserve{{ template "suffix" . }}-certificate
