apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prefix" . }}identity
  name: {{ template "prefix" . }}identity
spec:
  replicas: {{ .Values.application.identity.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ template "prefix" . }}identity
    spec:
      containers:
      - name: identity
        image: {{ .Values.application.identity.serviceImage }}:{{ .Values.application.identity.tag }}
{{- if .Values.application.identity.command }}
        command:
{{ range .Values.application.identity.command }}
        - {{ . }}
{{ end }}
{{- end }}
{{- if .Values.application.identity.args }}
        args:
{{ range .Values.application.identity.args }}
        - {{ . }}
{{ end }}
{{- end }}
        # envFrom:
        # - configMapRef:
        #     name: {{ template "prefix" . }}identity
        # envFrom:
        # - secretRef:
        #     name: {{ template "prefix" . }}identity
        env:
        - name: Serilog__MinimumLevel__Default
          value: Information
{{- if .Values.application.identity.env }}
{{ range $key, $value := .Values.application.identity.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{ end }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /info
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: 8443
          protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /info
        #     port: 8443
        #     scheme: HTTPS
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        resources:
          limits:
            cpu: 128m
            memory: 128Mi
          requests:
            cpu: 64m
            memory: 64Mi
        # # Will be available with Kubernetes 1.20
        # startupProbe:
        #   httpGet:
        #     path: /info
        #     port: 8443
        #   failureThreshold: 60
        #   periodSeconds: 5
        volumeMounts:
        # - name: config-files
        #   mountPath: /etc/cexiolabs/cexiopay.identity/
        #   readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexiopay.identity/ssl/
        - name: secret-files
          mountPath: /etc/cexiolabs/cexiopay.identity/secrets/
      volumes:
      # - name: config-files
      #   configMap:
      #     name: {{ template "prefix" . }}identity-files
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}identity-certificate
      - name: secret-files
        secret:
          secretName: {{ template "prefix" . }}identity
