{{ if or (and (ne .Values.zone "test") (ne .Values.zone "production")) (ne .Release.Name "blue") }}
# In "test" and "production" zones on "blue" release, the "board" is hosted on GitHub Pages:
# - https://github.com/cexiolabs/cexpay.board-production-hosting
# - https://github.com/cexiolabs/cexpay.board-test-hosting
# so we deploy this conditionally
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}board
  name: {{ template "prefix" . }}board
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}board
  replicas: {{ .Values.application.board.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
        cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
        cexpay.io/ci.job: {{ .Values.ci.job | quote }}
        cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
      labels:
        app: {{ template "prefix" . }}board
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: board
        image: {{ .Values.application.board.serviceImage }}:{{ .Values.application.board.tag }}
{{- if .Values.application.board.command }}
        command:
{{- range .Values.application.board.command }}
        - {{ . }}
{{- end }}
{{- end }}
        args:
        - "--use-ssl"
{{- if .Values.application.board.args }}
{{- range .Values.application.board.args }}
        - {{ . }}
{{- end }}
{{- end }}
        env:
{{- if .Values.application.board.env }}
{{- range $key, $value := .Values.application.board.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        - name: BASE_PATH
          value: /
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 60
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 32m
            memory: 32Mi
        volumeMounts:
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexpay.board/ssl/
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}board-certificate
{{ end }}
