{{ if eq .Release.Name "blue" }}
# Right now "processing" is not able to work in few process
# so we deploy this conditionally
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}processing
  name: {{ template "prefix" . }}processing
spec:
  selector:
    matchLabels:
      app: {{ template "prefix" . }}processing
  replicas: {{ .Values.application.processing.replicas | default 0 }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
        cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
        cexpay.io/ci.job: {{ .Values.ci.job | quote }}
        cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
      labels:
        app: {{ template "prefix" . }}processing
    spec:
{{- if .Values.misc }}
{{- if .Values.misc.excludeHypervisors }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hypervisor
                operator: NotIn
                values:
{{- range .Values.misc.excludeHypervisors }}
                - {{ . }}
{{- end }}
{{- end }}
{{- end }}
      containers:
      - name: processing
        image: {{ .Values.application.processing.serviceImage }}:{{ .Values.application.processing.tag }}
{{- if .Values.application.processing.command }}
        command:
{{- range .Values.application.processing.command }}
        - {{ . }}
{{- end }}
{{- end }}
{{- if .Values.application.processing.args }}
        args:
{{- range .Values.application.processing.args }}
        - {{ . }}
{{- end }}
{{- end }}
        ports:
        # Main Web server
        - containerPort: 8080
          protocol: TCP
        # Dashboard API Web server
        - containerPort: 8082
          protocol: TCP
{{- if or (eq .Values.zone "evolution") (eq .Values.zone "presentation") }}
        # Swagger and welcome page used in "evolution" and "presentation" only, 
        - containerPort: 8083
          protocol: TCP
{{- end }}
{{- if or (eq .Values.zone "test") (eq .Values.zone "production") }}
        # In "evolution" and "presentation" we use proxy-service called "notifier", 
        # to handle callbacks via WebSocket, so we do need this port
        # for "test" and "production" only
        - containerPort: 8084
          protocol: TCP
{{- end }}
        # Gateway API Web server
        - containerPort: 8085
          protocol: TCP
        # WS server
        - containerPort: 8086
          protocol: TCP
        # Monitoring Web server
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config-files
          mountPath: /etc/cexiolabs/cexpay/
          readOnly: true
        - name: secret-certificate
          mountPath: /etc/cexiolabs/cexpay/ssl/
          readOnly: true
        - name: secret-files
          mountPath: /etc/cexiolabs/cexpay/secrets/
          # The service will delete all files after read its. So need write access.
          readOnly: false
        envFrom:
        - configMapRef:
            name: {{ template "prefix" . }}processing-envvars
        env:
{{- if .Values.application.processing.env }}
{{- range $key, $value := .Values.application.processing.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        - name: LOG_LEVEL
          value: info
        # livenessProbe:
        #   httpGet:
        #     path: /livenessProbe
        #     port: 9090
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/time
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 512m
            memory: 1024Mi
          requests:
            cpu: 128m
            memory: 256Mi
{{- if ne .Values.zone "production" }}
      imagePullSecrets:
      - name: cexpay-registry
{{- end }}
      volumes:
      - name: config-files
        configMap:
          name: {{ template "prefix" . }}processing-files
      - name: secret-files
        secret:
          secretName: {{ template "prefix" . }}processing
      - name: secret-certificate
        secret:
          secretName: {{ template "prefix" . }}processing-certificate
{{ end }}
