{{ $rootScope := . }}
{{- range $key, $value := .Values.ingress -}}
{{- if or (eq $rootScope.Release.Name "tag") (eq $value.type "internal") }}
# Skip external ingress for non-tag release
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $rootScope.Chart.Name }}-{{ $key | lower }}{{ template "suffix" $rootScope }}
  annotations:
{{ if $value.backendCaSecretName }}
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ $rootScope.Release.Namespace }}/{{ .backendCaSecretName }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
{{ end }}
{{ if $value.backendInsecure }}
    nginx.ingress.kubernetes.io/backend-protocol: "http"
    nginx.ingress.kubernetes.io/secure-backends: "false"
{{ else }}
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.org/ssl-services: {{ range $bindPath, $serviceConnectivity := $value.paths }}{{ $rootScope.Chart.Name }}-{{ $serviceConnectivity.backendServiceName }}{{ template "suffix" $rootScope }}{{ end }}
{{ end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
      expires off;
      etag off;
spec:
  tls:
    - hosts:
        - "{{ template "prefix" $rootScope }}{{ $value.domain }}"
      secretName: "{{ $value.certSecretName }}"
  rules:
    - host: "{{ template "prefix" $rootScope }}{{ $value.domain }}"
      http:
        paths:
{{ range $bindPath, $serviceConnectivity := $value.paths }}
          - backend:
              serviceName: {{ $rootScope.Chart.Name }}-{{ $serviceConnectivity.backendServiceName }}{{ template "suffix" $rootScope }}
              servicePort: {{ $serviceConnectivity.backendServicePort }}
            path: {{ $bindPath }}
{{ end }}
---
{{- end }}
{{- end -}}
