apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prefix" . }}messengerbridge
  name: {{ template "prefix" . }}messengerbridge
spec:
  ports:
    - port: 8443
      name: messengerbridge
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}messengerbridge
