apiVersion: v1
kind: Service
metadata:
  labels:
    app: api{{ template "suffix" . }}
  name: api{{ template "suffix" . }}
spec:
  ports:
    - port: 8443
      name: api
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: api{{ template "suffix" . }}
