apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prefix" . }}gateintegrationdemo
  name: {{ template "prefix" . }}gateintegrationdemo
spec:
  ports:
    - port: 8443
      name: gateintegrationdemo
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}gateintegrationdemo
