{{ if and (ne .Values.zone "production") (eq .Release.Name "blue") }}
# 1) In "production" zone, the "landing" is hosted on GitHub Pages:
# - https://github.com/cexiolabs/cexpay.landing-hosting
# 2) In non "production" zones deploy for "blue" release ONLY
# so we deploy this conditionally
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prefix" . }}landing
  name: {{ template "prefix" . }}landing
spec:
  ports:
    - port: 8443
      name: landing
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}landing
{{ end }}
