{{- if ne .Values.zone "production" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prefix" . }}statuspage
  name: {{ template "prefix" . }}statuspage
spec:
  ports:
    - port: 8443
      name: statuspage
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}statuspage
{{- end }}
