apiVersion: v1
kind: Service
metadata:
  annotations:
    cexpay.io/version: {{ .Chart.AppVersion | quote }}
{{- if .Values.ci }}
    cexpay.io/ci.tag: {{ .Values.ci.tag | quote }}
    cexpay.io/ci.job: {{ .Values.ci.job | quote }}
    cexpay.io/ci.pipeline: {{ .Values.ci.pipeline | quote }}
{{- end }}
  labels:
    app: {{ template "prefix" . }}messengerbridge
  name: {{ template "prefix" . }}messengerbridge
spec:
  ports:
    - port: 8443
      name: messengerbridge
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}messengerbridge
