{{- if ne .Values.zone "production" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prefix" . }}ptinvoice
  name: {{ template "prefix" . }}ptinvoice
spec:
  ports:
    - port: 8443
      name: ptinvoice
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}ptinvoice
{{- end }}
