apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prefix" . }}api
  name: {{ template "prefix" . }}api
spec:
  ports:
    - port: 8443
      name: api
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: {{ template "prefix" . }}api
