# kubectl --context cppreprd get --output=yaml ConfigMap/processing-envvars

apiVersion: v1
kind: ConfigMap
metadata:
  name: processing-envvars
  namespace: cryptopay
data:
  runtime.aggregator.url: wss://externalapi.aggrprod.kube/ws
  runtime.wtf2pss.url: https://provider-wtf2.prodpss.kube/api