{
 "title": "Cryptopay-Health",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "evolution, presentation" },
   {
    "name": "service",
    "label": "Service",
    "query": "query_result(max_over_time(process_start_time_seconds{kubernetes_namespace=\"cryptopay-$env\"}[${__range}]))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(max_over_time(process_start_time_seconds{kubernetes_name=~\"${service}\", kubernetes_namespace=\"cryptopay-$env\"}[${__range}]))"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "singlestat",
   "description": "Total requests",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "singlestat",
   "description": "Total count of successful request",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status_code=~\"[23].*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "2xx, 3xx %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status_code=~\"[23].*\"}[$__range]))) / (sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "4xx %",
   "type": "singlestat",
   "description": "Percentage of 4xx responses",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status_code=~\"[4].*\"}[$__range]))) / (sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "5xx %",
   "type": "singlestat",
   "description": "Percentage of 5xx responses",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status_code=~\"[5].*\"}[$__range]))) / (sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "General Errors",
   "type": "singlestat",
   "description": "Total count of general errors",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(general_errors{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Critical Errors",
   "type": "singlestat",
   "description": "Total count of critical errors",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(critical_errors{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]))"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max_over_time(process_start_time_seconds{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\"}[${__range}]) * 1000"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average Response Time",
   "type": "graph",
   "description": "Average response time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_sum{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range])) / sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]))",
     "legendFormat": "Average response time"
    }
   ]
  },
  {
   "title": "Top-20 Failed Requests",
   "type": "table",
   "description": "Top-20 Failed Requests",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "topk(20, sort_desc(sum(increase(http_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status_code=~\"[45].*\"}[$__range]) > 0) by (method, path, status_code, pod, app_version, kubernetes_name)))"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "heatmap",
   "description": "Response time distribution",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Process CPU usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate(process_cpu_seconds_total{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "description": "Process RAM usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "description": "NodeJS Event Loop Lag",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_lag_seconds{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "graph",
   "description": "Process virtual memory usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Database Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Postgres Query Time Distrbution",
   "type": "heatmap",
   "description": "Postgres query time distribution",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(pgsql_query_duration_seconds_bucket{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top 20 Frequently Used Queries",
   "type": "table",
   "description": "Hashes of Top 20 frequently used queries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 49 },
   "targets": [
    {
     "expr": "sort_desc(topk(20, sort_desc(sum(increase(pgsql_query_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]) > 0) by (hash))))"
    }
   ]
  },
  {
   "title": "Top 20 Long Running Queries",
   "type": "table",
   "description": "Hashes of Top 20 long running queries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 49 },
   "targets": [
    {
     "expr": "sort_desc(topk(20,sort_desc(topk(20, sort_desc(sum(increase(pgsql_query_duration_seconds_sum{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]) > 0) by (hash) / sum(increase(pgsql_query_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__range]) > 0) by (hash))))))"
    }
   ]
  },
  { "title": "Wtf Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Wtf Requests Count / Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(wtf_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[1h])) * 3600",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Wtf Failed Requests %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (wtf_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status!~\"[2,3].*\"})) / (sum by (pod) (wtf_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Wtf Response Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(wtf_request_duration_seconds_bucket{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Aggregator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Aggregator Requests Count / Hour",
   "type": "graph",
   "description": "Aggregator requests count per hour",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(aggregator_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[1h])) * 3600",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Aggregator Failed Requests %",
   "type": "graph",
   "description": "Percent of failed requests to Aggregator",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (aggregator_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\", status!=\"OK\"})) / (sum by (pod) (aggregator_request_duration_seconds_count{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Aggregator Response Time Distrbution",
   "type": "heatmap",
   "description": "Aggregator response time distribution",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "sum(increase(aggregator_request_duration_seconds_bucket{kubernetes_namespace=\"cryptopay-$env\", kubernetes_name=~\"$service\", pod=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}