# kubectl --namespace cexpay-admin get --output=yaml ConfigMap/gatehostinternal-files
# kubectl --namespace cexpay-admin get --output=json ConfigMap/gatehostinternal-files | jq -r ".data" | yq eval -P | sed 's/^/  /'
# kubectl --namespace cexpay-admin apply --filename=runtime.configmaps/production/gatehostinternal-files.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: gatehostinternal-files
  namespace: cexpay-admin
