apiVersion: v1
kind: ConfigMap
metadata:
  name: processing-envvars
  namespace: cryptopay
data:
  runtime.aggregator.url: wss://externalapi.aggrprod.kube/ws
  runtime.pss.cryptoWalletHelper.url: https://rpc.prodpss.kube/cryptopay
  runtime.wtf2pss.url: https://provider-wtf2.prodpss.kube