version: '3.7'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - published: 6379
        target: 6379
        protocol: tcp

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
      - published: 8081
        target: 8081
        protocol: tcp
